#Transformación y modelos de Machine Learning

## Librerías

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score
import sklearn.metrics as metrics
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

## Cargue de datos

In [ ]:
data = pd.read_csv("input_modelo.csv")

In [ ]:
data

         Unnamed: 0   Año  Mes  ...    Categoria Nevera Target
0                 0  2019    5  ...  Categoria_2      1      0
1                 1  2019    5  ...  Categoria_2      1      0
2                 2  2019    5  ...  Categoria_2      1      0
3                 3  2019    5  ...  Categoria_2      1      0
4                 4  2019    5  ...  Categoria_2      1      0
...             ...   ...  ...  ...          ...    ...    ...
1406111     1406111  2020    8  ...  Categoria_2      0      5
1406112     1406112  2020    7  ...  Categoria_6      0      4
1406113     1406113  2020    7  ...  Categoria_6      0      5
1406114     1406114  2020    9  ...  Categoria_6      0      4
1406115     1406115  2020    9  ...  Categoria_6      0      5

[1406116 rows x 17 columns]

In [ ]:
data_test = pd.read_csv("Input3_clientes_test.csv", sep=";")

## Modelos sin transformación de datos

In [ ]:
data_1 = data.copy()
data_1 = data_1.drop(['Año',	'Mes',	'SegmentoPrecio2',	'Marca2',	'Cupo2',	'CapacidadEnvase2',	'Volumen',	'disc',	'nr',	'Regional2',	'Gerencia2',	'SubCanal2',	'Categoria',	'Nevera'], axis=1)
data_1 = pd.get_dummies(data_1, columns=['Target'])
data_1 = data_1.rename(columns={"Target_1":"Marca1", "Target_2":"Marca2", "Target_3":"Marca3", "Target_4":"Marca_Inno1", "Target_5":"Marca_Inno2"})
data_1 = data_1.drop(["Target_0", "Unnamed: 0"], axis=1)
data_1

         Cliente  Marca1  Marca2  Marca3  Marca_Inno1  Marca_Inno2
0             10       0       0       0            0            0
1             10       0       0       0            0            0
2             10       0       0       0            0            0
3             10       0       0       0            0            0
4             10       0       0       0            0            0
...          ...     ...     ...     ...          ...          ...
1406111    20577       0       0       0            0            1
1406112    20580       0       0       0            1            0
1406113    20580       0       0       0            0            1
1406114    20580       0       0       0            1            0
1406115    20580       0       0       0            0            1

[1406116 rows x 6 columns]

In [ ]:
X = data_1.Cliente.values.reshape(-1,1)
y = data_1.drop(["Cliente"], axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

### Knn con 4 columnas target

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn1 = KNeighborsClassifier(n_neighbors=100)
knn1.fit(X_train, y_train)

# Predecimos sobre nuestro set de entrenamieto
y_train_pred = knn1.predict(X_train)

# Predecimos sobre nuestro set de test
y_test_pred = knn1.predict(X_test)

# Comaparamos con las etiquetas reales
print('Accuracy sobre conjunto de Train:', accuracy_score(y_train_pred,y_train))
print('Curva Roc sobre el test set: ', metrics.roc_auc_score(y_test, y_test_pred))

Accuracy sobre conjunto de Train: 0.9359207380819096
Curva Roc sobre el test set:  0.500819779572814

In [ ]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

knn1 = KNeighborsClassifier()
knn1.fit(X_train, y_train)

# Define los hyperparámetros

hp_candidates = [{'n_neighbors': np.arange(30, 60, 2),
                  'weights':['uniform','distance']}]

# Se busca mediante GridSearch el mejor hyperparámetro según los ya propuestos
grid = GridSearchCV(estimator=knn1, param_grid=hp_candidates, 
                    scoring="roc_auc", cv=5, verbose=5)

grid.fit(X_train, y_train)

# Se obtiene y se visualizan los mejor hiperparámetros encontrados con GridSearch
print(grid.best_score_)
print(grid.best_estimator_)
print(grid.best_params_)

Fitting 5 folds for each of 30 candidates, totalling 150 fits
[CV] n_neighbors=30, weights=uniform .................................

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.

[CV] ..... n_neighbors=30, weights=uniform, score=0.616, total=   6.7s
[CV] n_neighbors=30, weights=uniform .................................

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    6.8s remaining:    0.0s

[CV] ..... n_neighbors=30, weights=uniform, score=0.619, total=   6.6s
[CV] n_neighbors=30, weights=uniform .................................

[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:   13.4s remaining:    0.0s

[CV] ..... n_neighbors=30, weights=uniform, score=0.623, total=   6.9s
[CV] n_neighbors=30, weights=uniform .................................

[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:   20.2s remaining:    0.0s

[CV] ..... n_neighbors=30, weights=uniform, score=0.623, total=   6.8s
[CV] n_neighbors=30, weights=uniform .................................

[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:   27.0s remaining:    0.0s

[CV] ..... n_neighbors=30, weights=uniform, score=0.621, total=   6.7s
[CV] n_neighbors=30, weights=distance ................................
[CV] .... n_neighbors=30, weights=distance, score=0.613, total=   6.6s
[CV] n_neighbors=30, weights=distance ................................
[CV] .... n_neighbors=30, weights=distance, score=0.617, total=   6.8s
[CV] n_neighbors=30, weights=distance ................................
[CV] .... n_neighbors=30, weights=distance, score=0.619, total=   6.8s
[CV] n_neighbors=30, weights=distance ................................
[CV] .... n_neighbors=30, weights=distance, score=0.620, total=   6.7s
[CV] n_neighbors=30, weights=distance ................................
[CV] .... n_neighbors=30, weights=distance, score=0.618, total=   6.8s
[CV] n_neighbors=32, weights=uniform .................................
[CV] ..... n_neighbors=32, weights=uniform, score=0.621, total=   7.2s
[CV] n_neighbors=32, weights=uniform .................................
[CV] ..... n_neighbors=32, weights=uniform, score=0.623, total=   7.1s
[CV] n_neighbors=32, weights=uniform .................................
[CV] ..... n_neighbors=32, weights=uniform, score=0.625, total=   7.2s
[CV] n_neighbors=32, weights=uniform .................................
[CV] ..... n_neighbors=32, weights=uniform, score=0.626, total=   7.0s
[CV] n_neighbors=32, weights=uniform .................................
[CV] ..... n_neighbors=32, weights=uniform, score=0.625, total=   7.3s
[CV] n_neighbors=32, weights=distance ................................
[CV] .... n_neighbors=32, weights=distance, score=0.617, total=   7.1s
[CV] n_neighbors=32, weights=distance ................................
[CV] .... n_neighbors=32, weights=distance, score=0.620, total=   7.2s
[CV] n_neighbors=32, weights=distance ................................
[CV] .... n_neighbors=32, weights=distance, score=0.621, total=   7.3s
[CV] n_neighbors=32, weights=distance ................................
[CV] .... n_neighbors=32, weights=distance, score=0.623, total=   7.2s
[CV] n_neighbors=32, weights=distance ................................
[CV] .... n_neighbors=32, weights=distance, score=0.621, total=   7.3s
[CV] n_neighbors=34, weights=uniform .................................
[CV] ..... n_neighbors=34, weights=uniform, score=0.623, total=   7.3s
[CV] n_neighbors=34, weights=uniform .................................
[CV] ..... n_neighbors=34, weights=uniform, score=0.626, total=   7.4s
[CV] n_neighbors=34, weights=uniform .................................
[CV] ..... n_neighbors=34, weights=uniform, score=0.627, total=   7.4s
[CV] n_neighbors=34, weights=uniform .................................
[CV] ..... n_neighbors=34, weights=uniform, score=0.628, total=   7.5s
[CV] n_neighbors=34, weights=uniform .................................
[CV] ..... n_neighbors=34, weights=uniform, score=0.627, total=   7.5s
[CV] n_neighbors=34, weights=distance ................................
[CV] .... n_neighbors=34, weights=distance, score=0.618, total=   7.4s
[CV] n_neighbors=34, weights=distance ................................
[CV] .... n_neighbors=34, weights=distance, score=0.623, total=   7.5s
[CV] n_neighbors=34, weights=distance ................................
[CV] .... n_neighbors=34, weights=distance, score=0.624, total=   7.5s
[CV] n_neighbors=34, weights=distance ................................
[CV] .... n_neighbors=34, weights=distance, score=0.624, total=   7.2s
[CV] n_neighbors=34, weights=distance ................................
[CV] .... n_neighbors=34, weights=distance, score=0.624, total=   7.6s
[CV] n_neighbors=36, weights=uniform .................................
[CV] ..... n_neighbors=36, weights=uniform, score=0.626, total=   9.9s
[CV] n_neighbors=36, weights=uniform .................................
[CV] ..... n_neighbors=36, weights=uniform, score=0.628, total=   7.8s
[CV] n_neighbors=36, weights=uniform .................................
[CV] ..... n_neighbors=36, weights=uniform, score=0.629, total=   7.8s
[CV] n_neighbors=36, weights=uniform .................................
[CV] ..... n_neighbors=36, weights=uniform, score=0.631, total=   7.7s
[CV] n_neighbors=36, weights=uniform .................................
[CV] ..... n_neighbors=36, weights=uniform, score=0.630, total=   8.0s
[CV] n_neighbors=36, weights=distance ................................
[CV] .... n_neighbors=36, weights=distance, score=0.621, total=   7.9s
[CV] n_neighbors=36, weights=distance ................................
[CV] .... n_neighbors=36, weights=distance, score=0.625, total=   7.8s
[CV] n_neighbors=36, weights=distance ................................
[CV] .... n_neighbors=36, weights=distance, score=0.626, total=   7.9s
[CV] n_neighbors=36, weights=distance ................................
[CV] .... n_neighbors=36, weights=distance, score=0.628, total=   7.9s
[CV] n_neighbors=36, weights=distance ................................
[CV] .... n_neighbors=36, weights=distance, score=0.626, total=   7.9s
[CV] n_neighbors=38, weights=uniform .................................
[CV] ..... n_neighbors=38, weights=uniform, score=0.628, total=   8.6s
[CV] n_neighbors=38, weights=uniform .................................
[CV] ..... n_neighbors=38, weights=uniform, score=0.631, total=   8.7s
[CV] n_neighbors=38, weights=uniform .................................
[CV] ..... n_neighbors=38, weights=uniform, score=0.631, total=   8.8s
[CV] n_neighbors=38, weights=uniform .................................
[CV] ..... n_neighbors=38, weights=uniform, score=0.633, total=   8.5s
[CV] n_neighbors=38, weights=uniform .................................
[CV] ..... n_neighbors=38, weights=uniform, score=0.631, total=   8.4s
[CV] n_neighbors=38, weights=distance ................................
[CV] .... n_neighbors=38, weights=distance, score=0.624, total=   8.5s
[CV] n_neighbors=38, weights=distance ................................
[CV] .... n_neighbors=38, weights=distance, score=0.628, total=   8.4s
[CV] n_neighbors=38, weights=distance ................................
[CV] .... n_neighbors=38, weights=distance, score=0.628, total=   8.6s
[CV] n_neighbors=38, weights=distance ................................
[CV] .... n_neighbors=38, weights=distance, score=0.629, total=   8.3s
[CV] n_neighbors=38, weights=distance ................................
[CV] .... n_neighbors=38, weights=distance, score=0.628, total=   8.7s
[CV] n_neighbors=40, weights=uniform .................................
[CV] ..... n_neighbors=40, weights=uniform, score=0.631, total=   8.9s
[CV] n_neighbors=40, weights=uniform .................................
[CV] ..... n_neighbors=40, weights=uniform, score=0.633, total=   8.8s
[CV] n_neighbors=40, weights=uniform .................................
[CV] ..... n_neighbors=40, weights=uniform, score=0.633, total=   9.2s
[CV] n_neighbors=40, weights=uniform .................................
[CV] ..... n_neighbors=40, weights=uniform, score=0.634, total=   8.9s
[CV] n_neighbors=40, weights=uniform .................................
[CV] ..... n_neighbors=40, weights=uniform, score=0.633, total=   9.1s
[CV] n_neighbors=40, weights=distance ................................
[CV] .... n_neighbors=40, weights=distance, score=0.627, total=   9.0s
[CV] n_neighbors=40, weights=distance ................................
[CV] .... n_neighbors=40, weights=distance, score=0.631, total=   9.0s
[CV] n_neighbors=40, weights=distance ................................
[CV] .... n_neighbors=40, weights=distance, score=0.629, total=   9.0s
[CV] n_neighbors=40, weights=distance ................................
[CV] .... n_neighbors=40, weights=distance, score=0.631, total=   8.9s
[CV] n_neighbors=40, weights=distance ................................
[CV] .... n_neighbors=40, weights=distance, score=0.630, total=   9.2s
[CV] n_neighbors=42, weights=uniform .................................
[CV] ..... n_neighbors=42, weights=uniform, score=0.632, total=   9.6s
[CV] n_neighbors=42, weights=uniform .................................
[CV] ..... n_neighbors=42, weights=uniform, score=0.635, total=   9.4s
[CV] n_neighbors=42, weights=uniform .................................
[CV] ..... n_neighbors=42, weights=uniform, score=0.634, total=   9.6s
[CV] n_neighbors=42, weights=uniform .................................
[CV] ..... n_neighbors=42, weights=uniform, score=0.636, total=   9.6s
[CV] n_neighbors=42, weights=uniform .................................
[CV] ..... n_neighbors=42, weights=uniform, score=0.635, total=   9.6s
[CV] n_neighbors=42, weights=distance ................................
[CV] .... n_neighbors=42, weights=distance, score=0.628, total=   9.7s
[CV] n_neighbors=42, weights=distance ................................
[CV] .... n_neighbors=42, weights=distance, score=0.633, total=   9.5s
[CV] n_neighbors=42, weights=distance ................................
[CV] .... n_neighbors=42, weights=distance, score=0.630, total=   9.7s
[CV] n_neighbors=42, weights=distance ................................
[CV] .... n_neighbors=42, weights=distance, score=0.633, total=   9.7s
[CV] n_neighbors=42, weights=distance ................................
[CV] .... n_neighbors=42, weights=distance, score=0.632, total=   9.7s
[CV] n_neighbors=44, weights=uniform .................................
[CV] ..... n_neighbors=44, weights=uniform, score=0.635, total=   9.9s
[CV] n_neighbors=44, weights=uniform .................................
[CV] ..... n_neighbors=44, weights=uniform, score=0.636, total=   9.9s
[CV] n_neighbors=44, weights=uniform .................................
[CV] ..... n_neighbors=44, weights=uniform, score=0.636, total=   9.9s
[CV] n_neighbors=44, weights=uniform .................................
[CV] ..... n_neighbors=44, weights=uniform, score=0.638, total=  10.1s
[CV] n_neighbors=44, weights=uniform .................................
[CV] ..... n_neighbors=44, weights=uniform, score=0.636, total=  10.2s
[CV] n_neighbors=44, weights=distance ................................
[CV] .... n_neighbors=44, weights=distance, score=0.631, total=  10.2s
[CV] n_neighbors=44, weights=distance ................................
[CV] .... n_neighbors=44, weights=distance, score=0.634, total=  10.1s
[CV] n_neighbors=44, weights=distance ................................
[CV] .... n_neighbors=44, weights=distance, score=0.633, total=   9.9s
[CV] n_neighbors=44, weights=distance ................................
[CV] .... n_neighbors=44, weights=distance, score=0.635, total=   9.5s
[CV] n_neighbors=44, weights=distance ................................
[CV] .... n_neighbors=44, weights=distance, score=0.633, total=   9.7s
[CV] n_neighbors=46, weights=uniform .................................
[CV] ..... n_neighbors=46, weights=uniform, score=0.636, total=  10.0s
[CV] n_neighbors=46, weights=uniform .................................
[CV] ..... n_neighbors=46, weights=uniform, score=0.638, total=  10.2s
[CV] n_neighbors=46, weights=uniform .................................
[CV] ..... n_neighbors=46, weights=uniform, score=0.637, total=  10.1s
[CV] n_neighbors=46, weights=uniform .................................
[CV] ..... n_neighbors=46, weights=uniform, score=0.639, total=  10.2s
[CV] n_neighbors=46, weights=uniform .................................
[CV] ..... n_neighbors=46, weights=uniform, score=0.637, total=  10.0s
[CV] n_neighbors=46, weights=distance ................................
[CV] .... n_neighbors=46, weights=distance, score=0.632, total=  10.2s
[CV] n_neighbors=46, weights=distance ................................
[CV] .... n_neighbors=46, weights=distance, score=0.636, total=  10.3s
[CV] n_neighbors=46, weights=distance ................................
[CV] .... n_neighbors=46, weights=distance, score=0.634, total=  10.3s
[CV] n_neighbors=46, weights=distance ................................
[CV] .... n_neighbors=46, weights=distance, score=0.636, total=  10.2s
[CV] n_neighbors=46, weights=distance ................................
[CV] .... n_neighbors=46, weights=distance, score=0.634, total=  10.5s
[CV] n_neighbors=48, weights=uniform .................................
[CV] ..... n_neighbors=48, weights=uniform, score=0.638, total=  10.1s
[CV] n_neighbors=48, weights=uniform .................................
[CV] ..... n_neighbors=48, weights=uniform, score=0.639, total=  10.0s
[CV] n_neighbors=48, weights=uniform .................................
[CV] ..... n_neighbors=48, weights=uniform, score=0.638, total=  10.1s
[CV] n_neighbors=48, weights=uniform .................................
[CV] ..... n_neighbors=48, weights=uniform, score=0.640, total=  10.2s
[CV] n_neighbors=48, weights=uniform .................................
[CV] ..... n_neighbors=48, weights=uniform, score=0.637, total=  10.1s
[CV] n_neighbors=48, weights=distance ................................
[CV] .... n_neighbors=48, weights=distance, score=0.634, total=  11.4s
[CV] n_neighbors=48, weights=distance ................................
[CV] .... n_neighbors=48, weights=distance, score=0.637, total=  10.0s
[CV] n_neighbors=48, weights=distance ................................
[CV] .... n_neighbors=48, weights=distance, score=0.636, total=  10.0s
[CV] n_neighbors=48, weights=distance ................................
[CV] .... n_neighbors=48, weights=distance, score=0.637, total=  10.2s
[CV] n_neighbors=48, weights=distance ................................
[CV] .... n_neighbors=48, weights=distance, score=0.635, total=  10.3s
[CV] n_neighbors=50, weights=uniform .................................
[CV] ..... n_neighbors=50, weights=uniform, score=0.640, total=  10.7s
[CV] n_neighbors=50, weights=uniform .................................
[CV] ..... n_neighbors=50, weights=uniform, score=0.640, total=  10.9s
[CV] n_neighbors=50, weights=uniform .................................
[CV] ..... n_neighbors=50, weights=uniform, score=0.640, total=  10.7s
[CV] n_neighbors=50, weights=uniform .................................
[CV] ..... n_neighbors=50, weights=uniform, score=0.641, total=  10.7s
[CV] n_neighbors=50, weights=uniform .................................
[CV] ..... n_neighbors=50, weights=uniform, score=0.639, total=  10.9s
[CV] n_neighbors=50, weights=distance ................................
[CV] .... n_neighbors=50, weights=distance, score=0.635, total=  10.7s
[CV] n_neighbors=50, weights=distance ................................
[CV] .... n_neighbors=50, weights=distance, score=0.638, total=  10.9s
[CV] n_neighbors=50, weights=distance ................................
[CV] .... n_neighbors=50, weights=distance, score=0.638, total=  10.8s
[CV] n_neighbors=50, weights=distance ................................
[CV] .... n_neighbors=50, weights=distance, score=0.638, total=  10.6s
[CV] n_neighbors=50, weights=distance ................................
[CV] .... n_neighbors=50, weights=distance, score=0.638, total=  10.8s
[CV] n_neighbors=52, weights=uniform .................................
[CV] ..... n_neighbors=52, weights=uniform, score=0.640, total=  11.0s
[CV] n_neighbors=52, weights=uniform .................................
[CV] ..... n_neighbors=52, weights=uniform, score=0.642, total=  11.0s
[CV] n_neighbors=52, weights=uniform .................................
[CV] ..... n_neighbors=52, weights=uniform, score=0.642, total=  11.3s
[CV] n_neighbors=52, weights=uniform .................................
[CV] ..... n_neighbors=52, weights=uniform, score=0.643, total=  11.2s
[CV] n_neighbors=52, weights=uniform .................................
[CV] ..... n_neighbors=52, weights=uniform, score=0.640, total=  11.3s
[CV] n_neighbors=52, weights=distance ................................
[CV] .... n_neighbors=52, weights=distance, score=0.636, total=  11.2s
[CV] n_neighbors=52, weights=distance ................................
[CV] .... n_neighbors=52, weights=distance, score=0.640, total=  10.9s
[CV] n_neighbors=52, weights=distance ................................
[CV] .... n_neighbors=52, weights=distance, score=0.640, total=  11.5s
[CV] n_neighbors=52, weights=distance ................................
[CV] .... n_neighbors=52, weights=distance, score=0.640, total=  11.3s
[CV] n_neighbors=52, weights=distance ................................
[CV] .... n_neighbors=52, weights=distance, score=0.639, total=  11.0s
[CV] n_neighbors=54, weights=uniform .................................
[CV] ..... n_neighbors=54, weights=uniform, score=0.640, total=  11.8s
[CV] n_neighbors=54, weights=uniform .................................
[CV] ..... n_neighbors=54, weights=uniform, score=0.644, total=  11.7s
[CV] n_neighbors=54, weights=uniform .................................
[CV] ..... n_neighbors=54, weights=uniform, score=0.643, total=  11.7s
[CV] n_neighbors=54, weights=uniform .................................
[CV] ..... n_neighbors=54, weights=uniform, score=0.644, total=  11.7s
[CV] n_neighbors=54, weights=uniform .................................
[CV] ..... n_neighbors=54, weights=uniform, score=0.641, total=  11.9s
[CV] n_neighbors=54, weights=distance ................................
[CV] .... n_neighbors=54, weights=distance, score=0.637, total=  11.7s
[CV] n_neighbors=54, weights=distance ................................
[CV] .... n_neighbors=54, weights=distance, score=0.642, total=  11.6s
[CV] n_neighbors=54, weights=distance ................................
[CV] .... n_neighbors=54, weights=distance, score=0.641, total=  11.7s
[CV] n_neighbors=54, weights=distance ................................
[CV] .... n_neighbors=54, weights=distance, score=0.641, total=  11.6s
[CV] n_neighbors=54, weights=distance ................................
[CV] .... n_neighbors=54, weights=distance, score=0.640, total=  11.9s
[CV] n_neighbors=56, weights=uniform .................................
[CV] ..... n_neighbors=56, weights=uniform, score=0.642, total=  12.1s
[CV] n_neighbors=56, weights=uniform .................................
[CV] ..... n_neighbors=56, weights=uniform, score=0.646, total=  12.1s
[CV] n_neighbors=56, weights=uniform .................................
[CV] ..... n_neighbors=56, weights=uniform, score=0.643, total=  12.0s
[CV] n_neighbors=56, weights=uniform .................................
[CV] ..... n_neighbors=56, weights=uniform, score=0.646, total=  12.1s
[CV] n_neighbors=56, weights=uniform .................................
[CV] ..... n_neighbors=56, weights=uniform, score=0.643, total=  12.6s
[CV] n_neighbors=56, weights=distance ................................
[CV] .... n_neighbors=56, weights=distance, score=0.639, total=  12.2s
[CV] n_neighbors=56, weights=distance ................................
[CV] .... n_neighbors=56, weights=distance, score=0.645, total=  11.9s
[CV] n_neighbors=56, weights=distance ................................
[CV] .... n_neighbors=56, weights=distance, score=0.642, total=  11.9s
[CV] n_neighbors=56, weights=distance ................................
[CV] .... n_neighbors=56, weights=distance, score=0.642, total=  11.8s
[CV] n_neighbors=56, weights=distance ................................
[CV] .... n_neighbors=56, weights=distance, score=0.641, total=  12.0s
[CV] n_neighbors=58, weights=uniform .................................
[CV] ..... n_neighbors=58, weights=uniform, score=0.643, total=  12.2s
[CV] n_neighbors=58, weights=uniform .................................
[CV] ..... n_neighbors=58, weights=uniform, score=0.647, total=  12.3s
[CV] n_neighbors=58, weights=uniform .................................
[CV] ..... n_neighbors=58, weights=uniform, score=0.644, total=  12.4s
[CV] n_neighbors=58, weights=uniform .................................
[CV] ..... n_neighbors=58, weights=uniform, score=0.646, total=  12.4s
[CV] n_neighbors=58, weights=uniform .................................
[CV] ..... n_neighbors=58, weights=uniform, score=0.643, total=  12.4s

[Parallel(n_jobs=1)]: Done 150 out of 150 | elapsed: 24.2min finished

0.6446667091695315
KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=58, p=2,
                     weights='uniform')
{'n_neighbors': 58, 'weights': 'uniform'}

In [ ]:
knn1 = KNeighborsClassifier(n_neighbors = 29, weights = 'uniform')
knn1.fit(X_train, y_train)

# Predecimos sobre nuestro set de entrenamieto
y_train_pred = knn1.predict(X_train)

# Predecimos sobre nuestro set de test
y_test_pred = knn1.predict(X_test)

# Comaparamos con las etiquetas reales
print('Accuracy sobre conjunto de Train:', accuracy_score(y_train_pred,y_train))
print('Curva Roc sobre el test set: ', metrics.roc_auc_score(y_test, y_test_pred))

Accuracy sobre conjunto de Train: 0.9360050635946442
Curva Roc sobre el test set:  0.5018267554744751

In [ ]:
data_test_1 = data_test.copy()
data_test_1 = data_test_1.drop(["Marca1",	"Marca2",	"Marca3",	"Marca_Inno1",	"Marca_Inno2"], axis=1)
y_pred = knn1.predict(data_test.Cliente.values.reshape(-1,1))
y_pred = pd.DataFrame(y_pred)
data_test_1 = data_test_1.merge(y_pred, how = 'left',left_index = True, right_index = True)
data_test_1 = data_test_1.rename(columns={0:"Marca1", 1:"Marca2", 2:"Marca3", 3:"Marca_Inno1", 4:"Marca_Inno2"})
data_test_1

      Cliente  Marca1  Marca2  Marca3  Marca_Inno1  Marca_Inno2
0          10       0       0       0            0            0
1          12       0       0       0            0            0
2          14       0       0       0            0            0
3          15       0       0       0            0            0
4          18       0       0       0            0            0
...       ...     ...     ...     ...          ...          ...
9297    20186       0       0       0            0            1
9298    20261       0       0       0            0            1
9299    20309       0       0       0            0            1
9300    20360       0       0       0            1            0
9301    20569       0       0       0            1            0

[9302 rows x 6 columns]

In [ ]:
data_test_1.to_csv("test1.csv", sep=',', index=False)

### Random forest con 4 columnas target

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
clf = RandomForestClassifier(max_depth=10, n_estimators=10, random_state=30)
clf.fit(X_train,y_train)

# Predecimos sobre nuestro set de entrenamieto
y_train_pred = clf.predict(X_train)

# Predecimos sobre nuestro set de test
y_test_pred = clf.predict(X_test)

# Comaparamos con las etiquetas reales
print('Accuracy sobre conjunto de Train:', accuracy_score(y_train_pred,y_train))
print('Curva Roc sobre el test set: ', metrics.roc_auc_score(y_test, y_test_pred))

Accuracy sobre conjunto de Train: 0.9359197221118766
Curva Roc sobre el test set:  0.5003204493938198

In [ ]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

randF = RandomForestClassifier()
randF.fit(X_train, y_train)

# Define los hyperparámetros

hp_candidates = [{'n_estimators': np.arange(22,30, 2),
                  'max_depth':np.arange(18, 20, 2)}]

# Se busca mediante GridSearch el mejor hyperparámetro según los ya propuestos
grid = GridSearchCV(estimator=randF, param_grid=hp_candidates, 
                    scoring='roc_auc', cv=5, verbose=5)

grid.fit(X_train, y_train)

# Se obtiene y se visualizan los mejor hiperparámetros encontrados con GridSearch
print(grid.best_score_)
print(grid.best_estimator_)
print(grid.best_params_)

Fitting 5 folds for each of 50 candidates, totalling 250 fits
[CV] max_depth=10, n_estimators=10 ...................................

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.

[CV] ....... max_depth=10, n_estimators=10, score=0.598, total=  36.2s
[CV] max_depth=10, n_estimators=10 ...................................

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   36.2s remaining:    0.0s

[CV] ....... max_depth=10, n_estimators=10, score=0.595, total=  35.8s
[CV] max_depth=10, n_estimators=10 ...................................

[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:  1.2min remaining:    0.0s

[CV] ....... max_depth=10, n_estimators=10, score=0.595, total=  35.9s
[CV] max_depth=10, n_estimators=10 ...................................

[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:  1.8min remaining:    0.0s

[CV] ....... max_depth=10, n_estimators=10, score=0.598, total=  35.9s
[CV] max_depth=10, n_estimators=10 ...................................

[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:  2.4min remaining:    0.0s

[CV] ....... max_depth=10, n_estimators=10, score=0.597, total=  35.8s
[CV] max_depth=10, n_estimators=12 ...................................
[CV] ....... max_depth=10, n_estimators=12, score=0.596, total=  37.0s
[CV] max_depth=10, n_estimators=12 ...................................
[CV] ....... max_depth=10, n_estimators=12, score=0.598, total=  26.1s
[CV] max_depth=10, n_estimators=12 ...................................
[CV] ....... max_depth=10, n_estimators=12, score=0.597, total=  26.4s
[CV] max_depth=10, n_estimators=12 ...................................
[CV] ....... max_depth=10, n_estimators=12, score=0.599, total=  26.2s
[CV] max_depth=10, n_estimators=12 ...................................
[CV] ....... max_depth=10, n_estimators=12, score=0.598, total=  26.1s
[CV] max_depth=10, n_estimators=14 ...................................
[CV] ....... max_depth=10, n_estimators=14, score=0.597, total=  30.5s
[CV] max_depth=10, n_estimators=14 ...................................
[CV] ....... max_depth=10, n_estimators=14, score=0.596, total=  30.3s
[CV] max_depth=10, n_estimators=14 ...................................
[CV] ....... max_depth=10, n_estimators=14, score=0.598, total=  30.5s
[CV] max_depth=10, n_estimators=14 ...................................
[CV] ....... max_depth=10, n_estimators=14, score=0.600, total=  30.5s
[CV] max_depth=10, n_estimators=14 ...................................
[CV] ....... max_depth=10, n_estimators=14, score=0.603, total=  30.6s
[CV] max_depth=10, n_estimators=16 ...................................
[CV] ....... max_depth=10, n_estimators=16, score=0.595, total=  35.3s
[CV] max_depth=10, n_estimators=16 ...................................
[CV] ....... max_depth=10, n_estimators=16, score=0.599, total=  34.3s
[CV] max_depth=10, n_estimators=16 ...................................
[CV] ....... max_depth=10, n_estimators=16, score=0.600, total=  34.6s
[CV] max_depth=10, n_estimators=16 ...................................
[CV] ....... max_depth=10, n_estimators=16, score=0.599, total=  34.9s
[CV] max_depth=10, n_estimators=16 ...................................
[CV] ....... max_depth=10, n_estimators=16, score=0.599, total=  34.6s
[CV] max_depth=10, n_estimators=18 ...................................
[CV] ....... max_depth=10, n_estimators=18, score=0.597, total=  38.8s
[CV] max_depth=10, n_estimators=18 ...................................
[CV] ....... max_depth=10, n_estimators=18, score=0.598, total=  38.5s
[CV] max_depth=10, n_estimators=18 ...................................
[CV] ....... max_depth=10, n_estimators=18, score=0.599, total=  39.3s
[CV] max_depth=10, n_estimators=18 ...................................
[CV] ....... max_depth=10, n_estimators=18, score=0.601, total=  38.8s
[CV] max_depth=10, n_estimators=18 ...................................
[CV] ....... max_depth=10, n_estimators=18, score=0.600, total=  38.4s
[CV] max_depth=10, n_estimators=20 ...................................
[CV] ....... max_depth=10, n_estimators=20, score=0.595, total=  43.2s
[CV] max_depth=10, n_estimators=20 ...................................
[CV] ....... max_depth=10, n_estimators=20, score=0.600, total=  42.7s
[CV] max_depth=10, n_estimators=20 ...................................
[CV] ....... max_depth=10, n_estimators=20, score=0.599, total=  42.9s
[CV] max_depth=10, n_estimators=20 ...................................
[CV] ....... max_depth=10, n_estimators=20, score=0.602, total=  42.8s
[CV] max_depth=10, n_estimators=20 ...................................
[CV] ....... max_depth=10, n_estimators=20, score=0.601, total=  43.0s
[CV] max_depth=10, n_estimators=22 ...................................
[CV] ....... max_depth=10, n_estimators=22, score=0.597, total=  47.5s
[CV] max_depth=10, n_estimators=22 ...................................
[CV] ....... max_depth=10, n_estimators=22, score=0.601, total=  47.7s
[CV] max_depth=10, n_estimators=22 ...................................
[CV] ....... max_depth=10, n_estimators=22, score=0.599, total=  47.4s
[CV] max_depth=10, n_estimators=22 ...................................
[CV] ....... max_depth=10, n_estimators=22, score=0.603, total=  47.3s
[CV] max_depth=10, n_estimators=22 ...................................
[CV] ....... max_depth=10, n_estimators=22, score=0.598, total=  47.7s
[CV] max_depth=10, n_estimators=24 ...................................
[CV] ....... max_depth=10, n_estimators=24, score=0.599, total=  51.9s
[CV] max_depth=10, n_estimators=24 ...................................
[CV] ....... max_depth=10, n_estimators=24, score=0.602, total=  52.0s
[CV] max_depth=10, n_estimators=24 ...................................
[CV] ....... max_depth=10, n_estimators=24, score=0.601, total=  51.8s
[CV] max_depth=10, n_estimators=24 ...................................
[CV] ....... max_depth=10, n_estimators=24, score=0.603, total=  51.9s
[CV] max_depth=10, n_estimators=24 ...................................
[CV] ....... max_depth=10, n_estimators=24, score=0.599, total=  51.9s
[CV] max_depth=10, n_estimators=26 ...................................
[CV] ....... max_depth=10, n_estimators=26, score=0.598, total=  56.3s
[CV] max_depth=10, n_estimators=26 ...................................
[CV] ....... max_depth=10, n_estimators=26, score=0.602, total=  56.4s
[CV] max_depth=10, n_estimators=26 ...................................
[CV] ....... max_depth=10, n_estimators=26, score=0.602, total=  57.5s
[CV] max_depth=10, n_estimators=26 ...................................
[CV] ....... max_depth=10, n_estimators=26, score=0.603, total=  56.4s
[CV] max_depth=10, n_estimators=26 ...................................
[CV] ....... max_depth=10, n_estimators=26, score=0.601, total=  56.5s
[CV] max_depth=10, n_estimators=28 ...................................
[CV] ....... max_depth=10, n_estimators=28, score=0.596, total= 1.0min
[CV] max_depth=10, n_estimators=28 ...................................
[CV] ....... max_depth=10, n_estimators=28, score=0.602, total= 1.0min
[CV] max_depth=10, n_estimators=28 ...................................
[CV] ....... max_depth=10, n_estimators=28, score=0.599, total= 1.0min
[CV] max_depth=10, n_estimators=28 ...................................
[CV] ....... max_depth=10, n_estimators=28, score=0.602, total=  59.6s
[CV] max_depth=10, n_estimators=28 ...................................
[CV] ....... max_depth=10, n_estimators=28, score=0.603, total= 1.0min
[CV] max_depth=12, n_estimators=10 ...................................
[CV] ....... max_depth=12, n_estimators=10, score=0.603, total=  24.7s
[CV] max_depth=12, n_estimators=10 ...................................
[CV] ....... max_depth=12, n_estimators=10, score=0.610, total=  24.6s
[CV] max_depth=12, n_estimators=10 ...................................
[CV] ....... max_depth=12, n_estimators=10, score=0.606, total=  24.8s
[CV] max_depth=12, n_estimators=10 ...................................
[CV] ....... max_depth=12, n_estimators=10, score=0.608, total=  24.6s
[CV] max_depth=12, n_estimators=10 ...................................
[CV] ....... max_depth=12, n_estimators=10, score=0.609, total=  24.8s
[CV] max_depth=12, n_estimators=12 ...................................
[CV] ....... max_depth=12, n_estimators=12, score=0.603, total=  29.4s
[CV] max_depth=12, n_estimators=12 ...................................
[CV] ....... max_depth=12, n_estimators=12, score=0.609, total=  29.5s
[CV] max_depth=12, n_estimators=12 ...................................
[CV] ....... max_depth=12, n_estimators=12, score=0.606, total=  49.4s
[CV] max_depth=12, n_estimators=12 ...................................
[CV] ....... max_depth=12, n_estimators=12, score=0.606, total=  48.9s
[CV] max_depth=12, n_estimators=12 ...................................
[CV] ....... max_depth=12, n_estimators=12, score=0.608, total=  48.6s
[CV] max_depth=12, n_estimators=14 ...................................
[CV] ....... max_depth=12, n_estimators=14, score=0.608, total=  56.7s
[CV] max_depth=12, n_estimators=14 ...................................
[CV] ....... max_depth=12, n_estimators=14, score=0.611, total=  57.2s
[CV] max_depth=12, n_estimators=14 ...................................
[CV] ....... max_depth=12, n_estimators=14, score=0.608, total=  57.4s
[CV] max_depth=12, n_estimators=14 ...................................
[CV] ....... max_depth=12, n_estimators=14, score=0.606, total=  56.6s
[CV] max_depth=12, n_estimators=14 ...................................
[CV] ....... max_depth=12, n_estimators=14, score=0.609, total=  56.8s
[CV] max_depth=12, n_estimators=16 ...................................
[CV] ....... max_depth=12, n_estimators=16, score=0.607, total=  48.5s
[CV] max_depth=12, n_estimators=16 ...................................
[CV] ....... max_depth=12, n_estimators=16, score=0.612, total=  43.3s
[CV] max_depth=12, n_estimators=16 ...................................
[CV] ....... max_depth=12, n_estimators=16, score=0.607, total=  41.6s
[CV] max_depth=12, n_estimators=16 ...................................
[CV] ....... max_depth=12, n_estimators=16, score=0.610, total=  41.6s
[CV] max_depth=12, n_estimators=16 ...................................
[CV] ....... max_depth=12, n_estimators=16, score=0.612, total=  43.2s
[CV] max_depth=12, n_estimators=18 ...................................
[CV] ....... max_depth=12, n_estimators=18, score=0.609, total=  48.0s
[CV] max_depth=12, n_estimators=18 ...................................
[CV] ....... max_depth=12, n_estimators=18, score=0.609, total=  47.5s
[CV] max_depth=12, n_estimators=18 ...................................
[CV] ....... max_depth=12, n_estimators=18, score=0.612, total=  47.4s
[CV] max_depth=12, n_estimators=18 ...................................
[CV] ....... max_depth=12, n_estimators=18, score=0.615, total=  47.1s
[CV] max_depth=12, n_estimators=18 ...................................
[CV] ....... max_depth=12, n_estimators=18, score=0.612, total=  47.2s
[CV] max_depth=12, n_estimators=20 ...................................
[CV] ....... max_depth=12, n_estimators=20, score=0.613, total=  52.6s
[CV] max_depth=12, n_estimators=20 ...................................
[CV] ....... max_depth=12, n_estimators=20, score=0.613, total=  52.5s
[CV] max_depth=12, n_estimators=20 ...................................
[CV] ....... max_depth=12, n_estimators=20, score=0.612, total=  52.7s
[CV] max_depth=12, n_estimators=20 ...................................
[CV] ....... max_depth=12, n_estimators=20, score=0.611, total=  52.5s
[CV] max_depth=12, n_estimators=20 ...................................
[CV] ....... max_depth=12, n_estimators=20, score=0.612, total=  52.6s
[CV] max_depth=12, n_estimators=22 ...................................
[CV] ....... max_depth=12, n_estimators=22, score=0.609, total=  58.1s
[CV] max_depth=12, n_estimators=22 ...................................
[CV] ....... max_depth=12, n_estimators=22, score=0.611, total=  58.9s
[CV] max_depth=12, n_estimators=22 ...................................
[CV] ....... max_depth=12, n_estimators=22, score=0.613, total=  57.6s
[CV] max_depth=12, n_estimators=22 ...................................
[CV] ....... max_depth=12, n_estimators=22, score=0.612, total=  57.4s
[CV] max_depth=12, n_estimators=22 ...................................
[CV] ....... max_depth=12, n_estimators=22, score=0.617, total=  57.7s
[CV] max_depth=12, n_estimators=24 ...................................
[CV] ....... max_depth=12, n_estimators=24, score=0.608, total= 1.1min
[CV] max_depth=12, n_estimators=24 ...................................
[CV] ....... max_depth=12, n_estimators=24, score=0.613, total= 1.0min
[CV] max_depth=12, n_estimators=24 ...................................
[CV] ....... max_depth=12, n_estimators=24, score=0.608, total= 1.1min
[CV] max_depth=12, n_estimators=24 ...................................
[CV] ....... max_depth=12, n_estimators=24, score=0.612, total= 1.0min
[CV] max_depth=12, n_estimators=24 ...................................
[CV] ....... max_depth=12, n_estimators=24, score=0.615, total= 1.1min
[CV] max_depth=12, n_estimators=26 ...................................
[CV] ....... max_depth=12, n_estimators=26, score=0.608, total= 1.1min
[CV] max_depth=12, n_estimators=26 ...................................
[CV] ....... max_depth=12, n_estimators=26, score=0.614, total= 1.2min
[CV] max_depth=12, n_estimators=26 ...................................
[CV] ....... max_depth=12, n_estimators=26, score=0.611, total= 1.1min
[CV] max_depth=12, n_estimators=26 ...................................
[CV] ....... max_depth=12, n_estimators=26, score=0.614, total= 1.1min
[CV] max_depth=12, n_estimators=26 ...................................
[CV] ....... max_depth=12, n_estimators=26, score=0.613, total= 1.1min
[CV] max_depth=12, n_estimators=28 ...................................
[CV] ....... max_depth=12, n_estimators=28, score=0.609, total= 1.2min
[CV] max_depth=12, n_estimators=28 ...................................
[CV] ....... max_depth=12, n_estimators=28, score=0.615, total= 1.2min
[CV] max_depth=12, n_estimators=28 ...................................
[CV] ....... max_depth=12, n_estimators=28, score=0.610, total= 1.2min
[CV] max_depth=12, n_estimators=28 ...................................
[CV] ....... max_depth=12, n_estimators=28, score=0.610, total= 1.2min
[CV] max_depth=12, n_estimators=28 ...................................
[CV] ....... max_depth=12, n_estimators=28, score=0.615, total= 1.2min
[CV] max_depth=14, n_estimators=10 ...................................
[CV] ....... max_depth=14, n_estimators=10, score=0.617, total=  29.4s
[CV] max_depth=14, n_estimators=10 ...................................
[CV] ....... max_depth=14, n_estimators=10, score=0.618, total=  29.3s
[CV] max_depth=14, n_estimators=10 ...................................
[CV] ....... max_depth=14, n_estimators=10, score=0.618, total=  30.2s
[CV] max_depth=14, n_estimators=10 ...................................
[CV] ....... max_depth=14, n_estimators=10, score=0.617, total=  29.4s
[CV] max_depth=14, n_estimators=10 ...................................
[CV] ....... max_depth=14, n_estimators=10, score=0.620, total=  29.6s
[CV] max_depth=14, n_estimators=12 ...................................
[CV] ....... max_depth=14, n_estimators=12, score=0.621, total=  35.4s
[CV] max_depth=14, n_estimators=12 ...................................
[CV] ....... max_depth=14, n_estimators=12, score=0.618, total=  35.5s
[CV] max_depth=14, n_estimators=12 ...................................
[CV] ....... max_depth=14, n_estimators=12, score=0.619, total=  35.7s
[CV] max_depth=14, n_estimators=12 ...................................
[CV] ....... max_depth=14, n_estimators=12, score=0.617, total=  35.3s
[CV] max_depth=14, n_estimators=12 ...................................
[CV] ....... max_depth=14, n_estimators=12, score=0.622, total=  35.4s
[CV] max_depth=14, n_estimators=14 ...................................
[CV] ....... max_depth=14, n_estimators=14, score=0.619, total=  41.4s
[CV] max_depth=14, n_estimators=14 ...................................
[CV] ....... max_depth=14, n_estimators=14, score=0.618, total=  43.5s
[CV] max_depth=14, n_estimators=14 ...................................
[CV] ....... max_depth=14, n_estimators=14, score=0.619, total=  41.7s
[CV] max_depth=14, n_estimators=14 ...................................
[CV] ....... max_depth=14, n_estimators=14, score=0.623, total=  41.2s
[CV] max_depth=14, n_estimators=14 ...................................
[CV] ....... max_depth=14, n_estimators=14, score=0.621, total=  41.5s
[CV] max_depth=14, n_estimators=16 ...................................
[CV] ....... max_depth=14, n_estimators=16, score=0.620, total=  47.5s
[CV] max_depth=14, n_estimators=16 ...................................
[CV] ....... max_depth=14, n_estimators=16, score=0.620, total=  47.9s
[CV] max_depth=14, n_estimators=16 ...................................
[CV] ....... max_depth=14, n_estimators=16, score=0.620, total=  47.1s
[CV] max_depth=14, n_estimators=16 ...................................
[CV] ....... max_depth=14, n_estimators=16, score=0.622, total=  47.5s
[CV] max_depth=14, n_estimators=16 ...................................
[CV] ....... max_depth=14, n_estimators=16, score=0.625, total=  46.6s
[CV] max_depth=14, n_estimators=18 ...................................
[CV] ....... max_depth=14, n_estimators=18, score=0.622, total=  52.4s
[CV] max_depth=14, n_estimators=18 ...................................
[CV] ....... max_depth=14, n_estimators=18, score=0.624, total=  51.8s
[CV] max_depth=14, n_estimators=18 ...................................
[CV] ....... max_depth=14, n_estimators=18, score=0.621, total=  52.5s
[CV] max_depth=14, n_estimators=18 ...................................
[CV] ....... max_depth=14, n_estimators=18, score=0.625, total=  52.5s
[CV] max_depth=14, n_estimators=18 ...................................
[CV] ....... max_depth=14, n_estimators=18, score=0.623, total=  53.7s
[CV] max_depth=14, n_estimators=20 ...................................
[CV] ....... max_depth=14, n_estimators=20, score=0.618, total=  58.5s
[CV] max_depth=14, n_estimators=20 ...................................
[CV] ....... max_depth=14, n_estimators=20, score=0.624, total=  58.4s
[CV] max_depth=14, n_estimators=20 ...................................
[CV] ....... max_depth=14, n_estimators=20, score=0.621, total=  59.9s
[CV] max_depth=14, n_estimators=20 ...................................
[CV] ....... max_depth=14, n_estimators=20, score=0.623, total=  58.5s
[CV] max_depth=14, n_estimators=20 ...................................
[CV] ....... max_depth=14, n_estimators=20, score=0.625, total=  58.6s
[CV] max_depth=14, n_estimators=22 ...................................
[CV] ....... max_depth=14, n_estimators=22, score=0.621, total= 1.1min
[CV] max_depth=14, n_estimators=22 ...................................
[CV] ....... max_depth=14, n_estimators=22, score=0.624, total= 1.1min
[CV] max_depth=14, n_estimators=22 ...................................
[CV] ....... max_depth=14, n_estimators=22, score=0.621, total= 1.1min
[CV] max_depth=14, n_estimators=22 ...................................
[CV] ....... max_depth=14, n_estimators=22, score=0.624, total= 1.1min
[CV] max_depth=14, n_estimators=22 ...................................
[CV] ....... max_depth=14, n_estimators=22, score=0.626, total= 1.1min
[CV] max_depth=14, n_estimators=24 ...................................
[CV] ....... max_depth=14, n_estimators=24, score=0.622, total= 1.2min
[CV] max_depth=14, n_estimators=24 ...................................
[CV] ....... max_depth=14, n_estimators=24, score=0.624, total= 1.2min
[CV] max_depth=14, n_estimators=24 ...................................
[CV] ....... max_depth=14, n_estimators=24, score=0.623, total= 1.2min
[CV] max_depth=14, n_estimators=24 ...................................
[CV] ....... max_depth=14, n_estimators=24, score=0.624, total= 1.2min
[CV] max_depth=14, n_estimators=24 ...................................
[CV] ....... max_depth=14, n_estimators=24, score=0.624, total= 1.2min
[CV] max_depth=14, n_estimators=26 ...................................
[CV] ....... max_depth=14, n_estimators=26, score=0.621, total= 1.3min
[CV] max_depth=14, n_estimators=26 ...................................
[CV] ....... max_depth=14, n_estimators=26, score=0.625, total= 1.3min
[CV] max_depth=14, n_estimators=26 ...................................
[CV] ....... max_depth=14, n_estimators=26, score=0.626, total= 1.3min
[CV] max_depth=14, n_estimators=26 ...................................
[CV] ....... max_depth=14, n_estimators=26, score=0.623, total= 1.3min
[CV] max_depth=14, n_estimators=26 ...................................
[CV] ....... max_depth=14, n_estimators=26, score=0.623, total= 1.3min

[Parallel(n_jobs=1)]: Done 250 out of 250 | elapsed: 232.3min finished

0.6459904433390591
RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=18, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=28,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)
{'max_depth': 18, 'n_estimators': 28}

In [ ]:
clf = RandomForestClassifier(max_depth=18, n_estimators=28)
clf.fit(X_train,y_train)

# Predecimos sobre nuestro set de entrenamieto
y_train_pred = clf.predict(X_train)

# Predecimos sobre nuestro set de test
y_test_pred = clf.predict(X_test)

# Comaparamos con las etiquetas reales
print('Accuracy sobre conjunto de Train:', accuracy_score(y_train_pred,y_train))
print('Curva Roc sobre el test set: ', metrics.roc_auc_score(y_test, y_test_pred))

Accuracy sobre conjunto de Train: 0.9360995488077084
Curva Roc sobre el test set:  0.5012395705382603

In [ ]:
data_test_1 = data_test.copy()
data_test_1 = data_test_1.drop(["Marca1",	"Marca2",	"Marca3",	"Marca_Inno1",	"Marca_Inno2"], axis=1)
y_pred = clf.predict(data_test.Cliente.values.reshape(-1,1))
y_pred = pd.DataFrame(y_pred)
data_test_1 = data_test_1.merge(y_pred, how = 'left',left_index = True, right_index = True)
data_test_1 = data_test_1.rename(columns={0:"Marca1", 1:"Marca2", 2:"Marca3", 3:"Marca_Inno1", 4:"Marca_Inno2"})
data_test_1

      Cliente  Marca1  Marca2  Marca3  Marca_Inno1  Marca_Inno2
0          10       0       0       0            0            0
1          12       0       0       0            0            0
2          14       0       0       0            0            0
3          15       0       0       0            0            0
4          18       0       0       0            0            0
...       ...     ...     ...     ...          ...          ...
9297    20186       0       0       0            1            0
9298    20261       0       0       0            0            1
9299    20309       0       0       0            0            1
9300    20360       0       0       0            1            0
9301    20569       0       0       0            1            0

[9302 rows x 6 columns]

In [ ]:
data_test_1.to_csv("testclf.csv", sep=',', index=False)

### XGBoost con 4 Columnas

In [ ]:
from xgboost import XGBClassifier
from sklearn.multioutput import MultiOutputClassifier 
xgs = MultiOutputClassifier(XGBClassifier(max_depth=18, n_estimators=20))
xgs.fit(X_train,y_train)

# Predecimos sobre nuestro set de entrenamieto
y_train_pred = xgs.predict(X_train)

# Predecimos sobre nuestro set de test
y_test_pred = xgs.predict(X_test)

# Comaparamos con las etiquetas reales
print('Accuracy sobre el test set: ',metrics.accuracy_score(y_test, y_test_pred))
print('Curva Roc sobre el test set: ', metrics.roc_auc_score(y_test, y_test_pred))

Accuracy sobre el test set:  0.936098237462515
Curva Roc sobre el test set:  0.5004601032293167

In [ ]:
data_test_2 = data_test.copy()
data_test_2 = data_test_2.drop(["Marca1",	"Marca2",	"Marca3",	"Marca_Inno1",	"Marca_Inno2"], axis=1)
y_pred = xgs.predict(data_test.Cliente.values.reshape(-1,1))
y_pred = pd.DataFrame(y_pred)
data_test_2 = data_test_2.merge(y_pred, how = 'left',left_index = True, right_index = True)
data_test_2 = data_test_2.rename(columns={0:"Marca1", 1:"Marca2", 2:"Marca3", 3:"Marca_Inno1", 4:"Marca_Inno2"})
data_test_2

      Cliente  Marca1  Marca2  Marca3  Marca_Inno1  Marca_Inno2
0          10       0       0       0            0            0
1          12       0       0       0            0            0
2          14       0       0       0            0            0
3          15       0       0       0            0            0
4          18       0       0       0            0            0
...       ...     ...     ...     ...          ...          ...
9297    20186       0       0       0            0            1
9298    20261       0       0       0            0            1
9299    20309       0       0       0            0            1
9300    20360       0       0       0            1            0
9301    20569       0       0       0            1            0

[9302 rows x 6 columns]

In [ ]:
data_test_2.to_csv("testxgs.csv", sep=',', index=False)

## Modelo final con imputación

In [ ]:
clientes = pd.read_csv("Input1_clientes_estructura.csv", sep=";")
clientes

       Cliente   Regional2    Gerencia2    SubCanal2    Categoria  Nevera
0            1  Regional 1   Gerencia_1   Subcanal_1  Categoria_1       0
1            2  Regional 1   Gerencia_1   Subcanal_1  Categoria_1       0
2            3  Regional 1   Gerencia_1   Subcanal_1  Categoria_1       0
3            4  Regional 1   Gerencia_1   Subcanal_1  Categoria_1       1
4            5  Regional 1   Gerencia_1   Subcanal_1  Categoria_2       1
...        ...         ...          ...          ...          ...     ...
20916    20917  Regional 1   Gerencia_1  Subcanal_31  Categoria_2       0
20917    20918  Regional 1   Gerencia_4  Subcanal_31  Categoria_1       0
20918    20919  Regional 1   Gerencia_9  Subcanal_31  Categoria_1       0
20919    20920  Regional 1  Gerencia_10  Subcanal_31  Categoria_1       0
20920    20921  Regional 1   Gerencia_9  Subcanal_31  Categoria_1       0

[20921 rows x 6 columns]

In [ ]:
venta_1 = pd.read_csv("Input2_clientes_venta.csv", sep=";")
venta_1

          Año  Mes  Cliente  ...   Volumen       disc          nr
0        2019    5       10  ...  0.112229 -30.590603  900.328567
1        2019    5       10  ...  0.021734   0.000000  149.184463
2        2019    5       10  ...  0.043469   0.000000  359.625828
3        2019    5       10  ...  0.026345 -31.065261  134.748399
4        2019    5       10  ...  0.086938   0.000000  496.901005
...       ...  ...      ...  ...       ...        ...         ...
1406111  2020    8    20577  ...  0.039122   0.000000  544.150314
1406112  2020    7    20580  ...  0.000000   0.000000    0.000000
1406113  2020    7    20580  ...  0.058683   0.000000  759.218996
1406114  2020    9    20580  ...  0.000000   0.000000    0.000000
1406115  2020    9    20580  ...  0.019561   0.000000  269.150196

[1406116 rows x 10 columns]

In [ ]:
testeo = pd.read_csv("Input3_clientes_test.csv", sep=";")
testeo

      Cliente  Marca1  Marca2  Marca3  Marca_Inno1  Marca_Inno2
0          10     NaN     NaN     NaN          NaN          NaN
1          12     NaN     NaN     NaN          NaN          NaN
2          14     NaN     NaN     NaN          NaN          NaN
3          15     NaN     NaN     NaN          NaN          NaN
4          18     NaN     NaN     NaN          NaN          NaN
...       ...     ...     ...     ...          ...          ...
9297    20186     NaN     NaN     NaN          NaN          NaN
9298    20261     NaN     NaN     NaN          NaN          NaN
9299    20309     NaN     NaN     NaN          NaN          NaN
9300    20360     NaN     NaN     NaN          NaN          NaN
9301    20569     NaN     NaN     NaN          NaN          NaN

[9302 rows x 6 columns]

In [ ]:
testeo_prueba = testeo.copy()
testeo_prueba["Año"] = 2020
testeo_prueba["Mes"] = 10
testeo_prueba

      Cliente  Marca1  Marca2  Marca3  Marca_Inno1  Marca_Inno2   Año  Mes
0          10     NaN     NaN     NaN          NaN          NaN  2020   10
1          12     NaN     NaN     NaN          NaN          NaN  2020   10
2          14     NaN     NaN     NaN          NaN          NaN  2020   10
3          15     NaN     NaN     NaN          NaN          NaN  2020   10
4          18     NaN     NaN     NaN          NaN          NaN  2020   10
...       ...     ...     ...     ...          ...          ...   ...  ...
9297    20186     NaN     NaN     NaN          NaN          NaN  2020   10
9298    20261     NaN     NaN     NaN          NaN          NaN  2020   10
9299    20309     NaN     NaN     NaN          NaN          NaN  2020   10
9300    20360     NaN     NaN     NaN          NaN          NaN  2020   10
9301    20569     NaN     NaN     NaN          NaN          NaN  2020   10

[9302 rows x 8 columns]

In [ ]:
cols = testeo_prueba.columns.tolist()
cols = cols[-2:] + cols[:-2]
testeo_prueba = testeo_prueba[cols]
testeo_prueba

       Año  Mes  Cliente  Marca1  Marca2  Marca3  Marca_Inno1  Marca_Inno2
0     2020   10       10     NaN     NaN     NaN          NaN          NaN
1     2020   10       12     NaN     NaN     NaN          NaN          NaN
2     2020   10       14     NaN     NaN     NaN          NaN          NaN
3     2020   10       15     NaN     NaN     NaN          NaN          NaN
4     2020   10       18     NaN     NaN     NaN          NaN          NaN
...    ...  ...      ...     ...     ...     ...          ...          ...
9297  2020   10    20186     NaN     NaN     NaN          NaN          NaN
9298  2020   10    20261     NaN     NaN     NaN          NaN          NaN
9299  2020   10    20309     NaN     NaN     NaN          NaN          NaN
9300  2020   10    20360     NaN     NaN     NaN          NaN          NaN
9301  2020   10    20569     NaN     NaN     NaN          NaN          NaN

[9302 rows x 8 columns]

### Transformación y merge

In [ ]:
df_merge = venta_1.merge(clientes, left_on='Cliente', right_on='Cliente')
df_merge

          Año  Mes  Cliente  ...   SubCanal2    Categoria Nevera
0        2019    5       10  ...  Subcanal_1  Categoria_2      1
1        2019    5       10  ...  Subcanal_1  Categoria_2      1
2        2019    5       10  ...  Subcanal_1  Categoria_2      1
3        2019    5       10  ...  Subcanal_1  Categoria_2      1
4        2019    5       10  ...  Subcanal_1  Categoria_2      1
...       ...  ...      ...  ...         ...          ...    ...
1406111  2020    8    20577  ...  Subcanal_3  Categoria_2      0
1406112  2020    7    20580  ...  Subcanal_5  Categoria_6      0
1406113  2020    7    20580  ...  Subcanal_5  Categoria_6      0
1406114  2020    9    20580  ...  Subcanal_5  Categoria_6      0
1406115  2020    9    20580  ...  Subcanal_5  Categoria_6      0

[1406116 rows x 15 columns]

In [ ]:
df_merge = pd.merge(df_merge, testeo_prueba,  how='left', left_on=['Año','Mes', 'Cliente'], right_on = ['Año','Mes', 'Cliente'])
df_merge

          Año  Mes  Cliente  ... Marca3 Marca_Inno1 Marca_Inno2
0        2019    5       10  ...    NaN         NaN         NaN
1        2019    5       10  ...    NaN         NaN         NaN
2        2019    5       10  ...    NaN         NaN         NaN
3        2019    5       10  ...    NaN         NaN         NaN
4        2019    5       10  ...    NaN         NaN         NaN
...       ...  ...      ...  ...    ...         ...         ...
1406111  2020    8    20577  ...    NaN         NaN         NaN
1406112  2020    7    20580  ...    NaN         NaN         NaN
1406113  2020    7    20580  ...    NaN         NaN         NaN
1406114  2020    9    20580  ...    NaN         NaN         NaN
1406115  2020    9    20580  ...    NaN         NaN         NaN

[1406116 rows x 20 columns]

In [ ]:
filter = (df_merge['Marca2_x'] == 'Marca_20') & (df_merge["Cupo2"] == "Cupo_3") & (df_merge["CapacidadEnvase2"] == "CapacidadEnvase_9")
df_merge.loc[filter, 'Marca1'] = 1

filter = (df_merge['Marca2_x'] == 'Marca_16') & (df_merge["Cupo2"] == "Cupo_2") & (df_merge["CapacidadEnvase2"] == "CapacidadEnvase_10")
df_merge.loc[filter, 'Marca2_y'] = 1

filter = (df_merge['Marca2_x'] == 'Marca_9') & (df_merge["Cupo2"] == "Cupo_3") & (df_merge["CapacidadEnvase2"] == "CapacidadEnvase_12")
df_merge.loc[filter, 'Marca3'] = 1

filter = (df_merge['Marca2_x'] == 'Marca_38') & (df_merge["Cupo2"] == "Cupo_2") & (df_merge["CapacidadEnvase2"] == "CapacidadEnvase_10")
df_merge.loc[filter, 'Marca_Inno1'] = 1

filter = (df_merge['Marca2_x'] == 'Marca_39') & (df_merge["Cupo2"] == "Cupo_2") & (df_merge["CapacidadEnvase2"] == "CapacidadEnvase_10")
df_merge.loc[filter, 'Marca_Inno2'] = 1

df_merge

          Año  Mes  Cliente  ... Marca3 Marca_Inno1 Marca_Inno2
0        2019    5       10  ...    NaN         NaN         NaN
1        2019    5       10  ...    NaN         NaN         NaN
2        2019    5       10  ...    NaN         NaN         NaN
3        2019    5       10  ...    NaN         NaN         NaN
4        2019    5       10  ...    NaN         NaN         NaN
...       ...  ...      ...  ...    ...         ...         ...
1406111  2020    8    20577  ...    NaN         NaN         1.0
1406112  2020    7    20580  ...    NaN         1.0         NaN
1406113  2020    7    20580  ...    NaN         NaN         1.0
1406114  2020    9    20580  ...    NaN         1.0         NaN
1406115  2020    9    20580  ...    NaN         NaN         1.0

[1406116 rows x 20 columns]

In [ ]:
df_merge = df_merge.drop(["Regional2"], axis=1)
df_merge

          Año  Mes  Cliente  ... Marca3 Marca_Inno1 Marca_Inno2
0        2019    5       10  ...    NaN         NaN         NaN
1        2019    5       10  ...    NaN         NaN         NaN
2        2019    5       10  ...    NaN         NaN         NaN
3        2019    5       10  ...    NaN         NaN         NaN
4        2019    5       10  ...    NaN         NaN         NaN
...       ...  ...      ...  ...    ...         ...         ...
1406111  2020    8    20577  ...    NaN         NaN         1.0
1406112  2020    7    20580  ...    NaN         1.0         NaN
1406113  2020    7    20580  ...    NaN         NaN         1.0
1406114  2020    9    20580  ...    NaN         1.0         NaN
1406115  2020    9    20580  ...    NaN         NaN         1.0

[1406116 rows x 19 columns]

In [ ]:
transform = df_merge.copy()

from sklearn.preprocessing import LabelEncoder

# creating instance of labelencoder
labelencoder = LabelEncoder()

# Assigning numerical values and storing in another column
transform['Marca2_x'] = labelencoder.fit_transform(transform['Marca2_x'])
transform['CapacidadEnvase2'] = labelencoder.fit_transform(transform['CapacidadEnvase2'])

transform

          Año  Mes  Cliente  ... Marca3  Marca_Inno1 Marca_Inno2
0        2019    5       10  ...    NaN          NaN         NaN
1        2019    5       10  ...    NaN          NaN         NaN
2        2019    5       10  ...    NaN          NaN         NaN
3        2019    5       10  ...    NaN          NaN         NaN
4        2019    5       10  ...    NaN          NaN         NaN
...       ...  ...      ...  ...    ...          ...         ...
1406111  2020    8    20577  ...    NaN          NaN         1.0
1406112  2020    7    20580  ...    NaN          1.0         NaN
1406113  2020    7    20580  ...    NaN          NaN         1.0
1406114  2020    9    20580  ...    NaN          1.0         NaN
1406115  2020    9    20580  ...    NaN          NaN         1.0

[1406116 rows x 19 columns]

In [ ]:
transform = pd.get_dummies(transform, columns=['SegmentoPrecio2','Cupo2','Gerencia2', 'SubCanal2', 'Categoria'])

transform

          Año  Mes  ...  Categoria_Categoria_5  Categoria_Categoria_6
0        2019    5  ...                      0                      0
1        2019    5  ...                      0                      0
2        2019    5  ...                      0                      0
3        2019    5  ...                      0                      0
4        2019    5  ...                      0                      0
...       ...  ...  ...                    ...                    ...
1406111  2020    8  ...                      0                      0
1406112  2020    7  ...                      0                      1
1406113  2020    7  ...                      0                      1
1406114  2020    9  ...                      0                      1
1406115  2020    9  ...                      0                      1

[1406116 rows x 66 columns]

In [ ]:
transform = transform.rename(columns={"Marca2_y":"Marca2"})
transform

          Año  Mes  ...  Categoria_Categoria_5  Categoria_Categoria_6
0        2019    5  ...                      0                      0
1        2019    5  ...                      0                      0
2        2019    5  ...                      0                      0
3        2019    5  ...                      0                      0
4        2019    5  ...                      0                      0
...       ...  ...  ...                    ...                    ...
1406111  2020    8  ...                      0                      0
1406112  2020    7  ...                      0                      1
1406113  2020    7  ...                      0                      1
1406114  2020    9  ...                      0                      1
1406115  2020    9  ...                      0                      1

[1406116 rows x 66 columns]

In [ ]:
transform = transform.fillna(0)
transform

          Año  Mes  ...  Categoria_Categoria_5  Categoria_Categoria_6
0        2019    5  ...                      0                      0
1        2019    5  ...                      0                      0
2        2019    5  ...                      0                      0
3        2019    5  ...                      0                      0
4        2019    5  ...                      0                      0
...       ...  ...  ...                    ...                    ...
1406111  2020    8  ...                      0                      0
1406112  2020    7  ...                      0                      1
1406113  2020    7  ...                      0                      1
1406114  2020    9  ...                      0                      1
1406115  2020    9  ...                      0                      1

[1406116 rows x 66 columns]

### Manejo de Outliers

In [ ]:
#Escojo solo los valores numéricos que tienen una distribución con colas muy largas



#volumen
q25,q75 = np.percentile(transform.Volumen.values, [25,75])
iqr = q75 - q25
minimo = q25 - 1.5*iqr
maximo = q75 + 1.5*iqr
transform = transform[(transform.Volumen >= minimo) & (transform.Volumen <= maximo)]

#disc
q25,q75 = np.percentile(transform.disc.values, [25,75])
iqr = q75 - q25
minimo = q25 - 1.5*iqr
maximo = q75 + 1.5*iqr
transform = transform[(data.disc >= minimo) & (transform.disc <= maximo)]

#nr
q25,q75 = np.percentile(transform.nr.values, [25,75])
iqr = q75 - q25
minimo = q25 - 1.5*iqr
maximo = q75 + 1.5*iqr
transform = transform[(transform.nr >= minimo) & (transform.nr <= maximo)]

### Filtro

In [ ]:

transform = transform.drop(transform[(transform['Marca1'] == 0.0) & (transform['Marca2'] == 0.0) & (transform['Marca3'] == 0.0) & (transform['Marca_Inno1'] == 0.0) & (transform['Marca_Inno2'] == 0.0)].index)
transform

          Año  Mes  ...  Categoria_Categoria_5  Categoria_Categoria_6
41       2019    9  ...                      0                      0
50       2019   10  ...                      0                      0
75       2020    1  ...                      0                      0
78       2020    2  ...                      0                      0
94       2019   12  ...                      0                      0
...       ...  ...  ...                    ...                    ...
1406111  2020    8  ...                      0                      0
1406112  2020    7  ...                      0                      1
1406113  2020    7  ...                      0                      1
1406114  2020    9  ...                      0                      1
1406115  2020    9  ...                      0                      1

[90099 rows x 66 columns]

In [116]:
transform2 = pd.merge(transform, testeo_prueba,  how='outer', 
                      left_on=['Año','Mes', 'Cliente', "Marca1",	"Marca2",	"Marca3",	"Marca_Inno1",	"Marca_Inno2"], 
                      right_on = ['Año','Mes', 'Cliente',"Marca1",	"Marca2",	"Marca3",	"Marca_Inno1",	"Marca_Inno2"])
transform2

        Año  Mes  ...  Categoria_Categoria_5  Categoria_Categoria_6
0      2019    9  ...                    0.0                    0.0
1      2019   10  ...                    0.0                    0.0
2      2020    1  ...                    0.0                    0.0
3      2020    2  ...                    0.0                    0.0
4      2019   12  ...                    0.0                    0.0
...     ...  ...  ...                    ...                    ...
99396  2020   10  ...                    NaN                    NaN
99397  2020   10  ...                    NaN                    NaN
99398  2020   10  ...                    NaN                    NaN
99399  2020   10  ...                    NaN                    NaN
99400  2020   10  ...                    NaN                    NaN

[99401 rows x 66 columns]

### Imputación de valores faltantes

In [109]:
from sklearn.impute import KNNImputer 
from sklearn.preprocessing import StandardScaler

#### Escalamos

In [117]:
scaler = StandardScaler()
transform2[['Marca2_x', 'CapacidadEnvase2', 'Volumen','disc', 'nr', 'Nevera', 'SegmentoPrecio2_SegmentoPrecio_1',
      'SegmentoPrecio2_SegmentoPrecio_2', 'SegmentoPrecio2_SegmentoPrecio_3',
      'Cupo2_Cupo_1', 'Cupo2_Cupo_2', 'Cupo2_Cupo_3', 'Cupo2_Cupo_4',
      'Cupo2_Cupo_5', 'Gerencia2_Gerencia_1', 'Gerencia2_Gerencia_10',
      'Gerencia2_Gerencia_11', 'Gerencia2_Gerencia_2', 
      'Gerencia2_Gerencia_3','Gerencia2_Gerencia_4', 
      'Gerencia2_Gerencia_5', 'Gerencia2_Gerencia_6',
      'Gerencia2_Gerencia_7', 'Gerencia2_Gerencia_8', 
      'Gerencia2_Gerencia_9','SubCanal2_Subcanal_1', 
      'SubCanal2_Subcanal_10','SubCanal2_Subcanal_11', 
      'SubCanal2_Subcanal_12','SubCanal2_Subcanal_13', 
      'SubCanal2_Subcanal_14','SubCanal2_Subcanal_15', 
      'SubCanal2_Subcanal_16',
      'SubCanal2_Subcanal_17', 'SubCanal2_Subcanal_18',
      'SubCanal2_Subcanal_19', 'SubCanal2_Subcanal_2',
      'SubCanal2_Subcanal_20', 'SubCanal2_Subcanal_21',
      'SubCanal2_Subcanal_22', 'SubCanal2_Subcanal_23',
      'SubCanal2_Subcanal_26', 'SubCanal2_Subcanal_28',
      'SubCanal2_Subcanal_3', 'SubCanal2_Subcanal_31',
      'SubCanal2_Subcanal_32', 'SubCanal2_Subcanal_4', 
      'SubCanal2_Subcanal_5',
      'SubCanal2_Subcanal_6', 'SubCanal2_Subcanal_7', 
      'SubCanal2_Subcanal_8',
      'SubCanal2_Subcanal_9', 'Categoria_Categoria_1',
      'Categoria_Categoria_2', 'Categoria_Categoria_3',
      'Categoria_Categoria_4', 'Categoria_Categoria_5',
      'Categoria_Categoria_6']] = scaler.fit_transform(
          transform2[['Marca2_x','CapacidadEnvase2', 'Volumen','disc', 'nr', 'Nevera', 'SegmentoPrecio2_SegmentoPrecio_1',
                'SegmentoPrecio2_SegmentoPrecio_2', 'SegmentoPrecio2_SegmentoPrecio_3',
                'Cupo2_Cupo_1', 'Cupo2_Cupo_2', 'Cupo2_Cupo_3', 'Cupo2_Cupo_4',
                'Cupo2_Cupo_5', 'Gerencia2_Gerencia_1', 'Gerencia2_Gerencia_10',
                'Gerencia2_Gerencia_11', 'Gerencia2_Gerencia_2', 'Gerencia2_Gerencia_3',
                'Gerencia2_Gerencia_4', 'Gerencia2_Gerencia_5', 'Gerencia2_Gerencia_6',
                'Gerencia2_Gerencia_7', 'Gerencia2_Gerencia_8', 'Gerencia2_Gerencia_9',
                'SubCanal2_Subcanal_1', 'SubCanal2_Subcanal_10',
                'SubCanal2_Subcanal_11', 'SubCanal2_Subcanal_12',
                'SubCanal2_Subcanal_13', 'SubCanal2_Subcanal_14',
                'SubCanal2_Subcanal_15', 'SubCanal2_Subcanal_16',
                'SubCanal2_Subcanal_17', 'SubCanal2_Subcanal_18',
                'SubCanal2_Subcanal_19', 'SubCanal2_Subcanal_2',
                'SubCanal2_Subcanal_20', 'SubCanal2_Subcanal_21',
                'SubCanal2_Subcanal_22', 'SubCanal2_Subcanal_23',
                'SubCanal2_Subcanal_26', 'SubCanal2_Subcanal_28',
                'SubCanal2_Subcanal_3', 'SubCanal2_Subcanal_31',
                'SubCanal2_Subcanal_32', 'SubCanal2_Subcanal_4', 'SubCanal2_Subcanal_5',
                'SubCanal2_Subcanal_6', 'SubCanal2_Subcanal_7', 'SubCanal2_Subcanal_8',
                'SubCanal2_Subcanal_9', 'Categoria_Categoria_1',
                'Categoria_Categoria_2', 'Categoria_Categoria_3',
                'Categoria_Categoria_4', 'Categoria_Categoria_5',
                'Categoria_Categoria_6']])
      
transform2

        Año  Mes  ...  Categoria_Categoria_5  Categoria_Categoria_6
0      2019    9  ...              -0.212393              -0.108168
1      2019   10  ...              -0.212393              -0.108168
2      2020    1  ...              -0.212393              -0.108168
3      2020    2  ...              -0.212393              -0.108168
4      2019   12  ...              -0.212393              -0.108168
...     ...  ...  ...                    ...                    ...
99396  2020   10  ...                    NaN                    NaN
99397  2020   10  ...                    NaN                    NaN
99398  2020   10  ...                    NaN                    NaN
99399  2020   10  ...                    NaN                    NaN
99400  2020   10  ...                    NaN                    NaN

[99401 rows x 66 columns]

#### Imputamos

In [118]:
transform2= transform2.sort_values(by=['Cliente'])
transform2 = transform2.reset_index()
transform2 = transform2.drop(["index"], axis=1)
transform2

        Año  Mes  ...  Categoria_Categoria_5  Categoria_Categoria_6
0      2020   10  ...                    NaN                    NaN
1      2020    8  ...              -0.212393              -0.108168
2      2020    8  ...              -0.212393              -0.108168
3      2020    9  ...              -0.212393              -0.108168
4      2020    9  ...              -0.212393              -0.108168
...     ...  ...  ...                    ...                    ...
99396  2020    8  ...              -0.212393              -0.108168
99397  2020    7  ...              -0.212393               9.244856
99398  2020    7  ...              -0.212393               9.244856
99399  2020    9  ...              -0.212393               9.244856
99400  2020    9  ...              -0.212393               9.244856

[99401 rows x 66 columns]

In [119]:
%%time

variable = transform2[['Marca2_x','CapacidadEnvase2', 'Volumen','disc', 'nr', 'Nevera', 'SegmentoPrecio2_SegmentoPrecio_1',
                'SegmentoPrecio2_SegmentoPrecio_2', 'SegmentoPrecio2_SegmentoPrecio_3',
                'Cupo2_Cupo_1', 'Cupo2_Cupo_2', 'Cupo2_Cupo_3', 'Cupo2_Cupo_4',
                'Cupo2_Cupo_5', 'Gerencia2_Gerencia_1', 'Gerencia2_Gerencia_10',
                'Gerencia2_Gerencia_11', 'Gerencia2_Gerencia_2', 'Gerencia2_Gerencia_3',
                'Gerencia2_Gerencia_4', 'Gerencia2_Gerencia_5', 'Gerencia2_Gerencia_6',
                'Gerencia2_Gerencia_7', 'Gerencia2_Gerencia_8', 'Gerencia2_Gerencia_9',
                'SubCanal2_Subcanal_1', 'SubCanal2_Subcanal_10',
                'SubCanal2_Subcanal_11', 'SubCanal2_Subcanal_12',
                'SubCanal2_Subcanal_13', 'SubCanal2_Subcanal_14',
                'SubCanal2_Subcanal_15', 'SubCanal2_Subcanal_16',
                'SubCanal2_Subcanal_17', 'SubCanal2_Subcanal_18',
                'SubCanal2_Subcanal_19', 'SubCanal2_Subcanal_2',
                'SubCanal2_Subcanal_20', 'SubCanal2_Subcanal_21',
                'SubCanal2_Subcanal_22', 'SubCanal2_Subcanal_23',
                'SubCanal2_Subcanal_26', 'SubCanal2_Subcanal_28',
                'SubCanal2_Subcanal_3', 'SubCanal2_Subcanal_31',
                'SubCanal2_Subcanal_32', 'SubCanal2_Subcanal_4', 'SubCanal2_Subcanal_5',
                'SubCanal2_Subcanal_6', 'SubCanal2_Subcanal_7', 'SubCanal2_Subcanal_8',
                'SubCanal2_Subcanal_9', 'Categoria_Categoria_1',
                'Categoria_Categoria_2', 'Categoria_Categoria_3',
                'Categoria_Categoria_4', 'Categoria_Categoria_5',
                'Categoria_Categoria_6']]
imputer = KNNImputer(n_neighbors=4,
    weights='distance',
    metric='nan_euclidean')
variable = imputer.fit_transform(variable)
transform2.loc[:, ['Marca2_x','CapacidadEnvase2', 'Volumen','disc', 'nr', 'Nevera', 'SegmentoPrecio2_SegmentoPrecio_1',
                'SegmentoPrecio2_SegmentoPrecio_2', 'SegmentoPrecio2_SegmentoPrecio_3',
                'Cupo2_Cupo_1', 'Cupo2_Cupo_2', 'Cupo2_Cupo_3', 'Cupo2_Cupo_4',
                'Cupo2_Cupo_5', 'Gerencia2_Gerencia_1', 'Gerencia2_Gerencia_10',
                'Gerencia2_Gerencia_11', 'Gerencia2_Gerencia_2', 'Gerencia2_Gerencia_3',
                'Gerencia2_Gerencia_4', 'Gerencia2_Gerencia_5', 'Gerencia2_Gerencia_6',
                'Gerencia2_Gerencia_7', 'Gerencia2_Gerencia_8', 'Gerencia2_Gerencia_9',
                'SubCanal2_Subcanal_1', 'SubCanal2_Subcanal_10',
                'SubCanal2_Subcanal_11', 'SubCanal2_Subcanal_12',
                'SubCanal2_Subcanal_13', 'SubCanal2_Subcanal_14',
                'SubCanal2_Subcanal_15', 'SubCanal2_Subcanal_16',
                'SubCanal2_Subcanal_17', 'SubCanal2_Subcanal_18',
                'SubCanal2_Subcanal_19', 'SubCanal2_Subcanal_2',
                'SubCanal2_Subcanal_20', 'SubCanal2_Subcanal_21',
                'SubCanal2_Subcanal_22', 'SubCanal2_Subcanal_23',
                'SubCanal2_Subcanal_26', 'SubCanal2_Subcanal_28',
                'SubCanal2_Subcanal_3', 'SubCanal2_Subcanal_31',
                'SubCanal2_Subcanal_32', 'SubCanal2_Subcanal_4', 'SubCanal2_Subcanal_5',
                'SubCanal2_Subcanal_6', 'SubCanal2_Subcanal_7', 'SubCanal2_Subcanal_8',
                'SubCanal2_Subcanal_9', 'Categoria_Categoria_1',
                'Categoria_Categoria_2', 'Categoria_Categoria_3',
                'Categoria_Categoria_4', 'Categoria_Categoria_5',
                'Categoria_Categoria_6']] = variable

CPU times: user 15min 16s, sys: 4.73 s, total: 15min 21s
Wall time: 15min 17s

In [120]:
transform2

        Año  Mes  ...  Categoria_Categoria_5  Categoria_Categoria_6
0      2020   10  ...          -1.644282e-17          -9.463493e-18
1      2020    8  ...          -2.123930e-01          -1.081683e-01
2      2020    8  ...          -2.123930e-01          -1.081683e-01
3      2020    9  ...          -2.123930e-01          -1.081683e-01
4      2020    9  ...          -2.123930e-01          -1.081683e-01
...     ...  ...  ...                    ...                    ...
99396  2020    8  ...          -2.123930e-01          -1.081683e-01
99397  2020    7  ...          -2.123930e-01           9.244856e+00
99398  2020    7  ...          -2.123930e-01           9.244856e+00
99399  2020    9  ...          -2.123930e-01           9.244856e+00
99400  2020    9  ...          -2.123930e-01           9.244856e+00

[99401 rows x 66 columns]

In [121]:
transform2["Date"] = transform2['Año'].map(str) + '-' + transform2['Mes'].map(str)
transform2["Date"] = pd.to_datetime(transform2["Date"])
transform2["Date"] = transform2["Date"].dt.to_period(freq = "M")
transform2 = transform2.drop(['Año', 'Mes'], axis=1)
cols = transform2.columns.tolist()
cols = cols[-1:] + cols[:-1]
transform2 = transform2[cols]
transform2

          Date  Cliente  ...  Categoria_Categoria_5  Categoria_Categoria_6
0      2020-10        1  ...          -1.644282e-17          -9.463493e-18
1      2020-08        1  ...          -2.123930e-01          -1.081683e-01
2      2020-08        1  ...          -2.123930e-01          -1.081683e-01
3      2020-09        1  ...          -2.123930e-01          -1.081683e-01
4      2020-09        1  ...          -2.123930e-01          -1.081683e-01
...        ...      ...  ...                    ...                    ...
99396  2020-08    20577  ...          -2.123930e-01          -1.081683e-01
99397  2020-07    20580  ...          -2.123930e-01           9.244856e+00
99398  2020-07    20580  ...          -2.123930e-01           9.244856e+00
99399  2020-09    20580  ...          -2.123930e-01           9.244856e+00
99400  2020-09    20580  ...          -2.123930e-01           9.244856e+00

[99401 rows x 65 columns]

In [122]:
transform2 = transform2.set_index(transform2['Date'])
transform2 = transform2.sort_index()
transform2 = transform2.drop(["Date"], axis=1)
transform2

         Cliente      Marca2_x  ...  Categoria_Categoria_5  Categoria_Categoria_6
Date                            ...
2019-05     1667  5.800108e-01  ...          -2.123930e-01          -1.081683e-01
2019-05     1273  5.800108e-01  ...          -2.123930e-01          -1.081683e-01
2019-05     6169  5.800108e-01  ...          -2.123930e-01          -1.081683e-01
2019-05     4281 -2.327741e+00  ...          -2.123930e-01          -1.081683e-01
2019-05     4281  5.800108e-01  ...          -2.123930e-01          -1.081683e-01
...          ...           ...  ...                    ...                    ...
2020-10     7426  7.002985e-17  ...          -1.644282e-17          -9.463493e-18
2020-10     7425  7.002985e-17  ...          -1.644282e-17          -9.463493e-18
2020-10     7424  7.002985e-17  ...          -1.644282e-17          -9.463493e-18
2020-10     7432  7.002985e-17  ...          -1.644282e-17          -9.463493e-18
2020-10        1  7.002985e-17  ...          -1.644282e-17          -9.463493e-18

[99401 rows x 64 columns]

### División de dataset para modelo

In [123]:
modelo = transform2['2019-05':'2020-09']
testeo_1  = transform2['2020-10':].reset_index()

In [124]:
train = modelo['2019-05':'2020-08'].reset_index()
test = modelo['2020-09':].reset_index()

In [125]:
train

          Date  Cliente  ...  Categoria_Categoria_5  Categoria_Categoria_6
0      2019-05     1667  ...              -0.212393              -0.108168
1      2019-05     1273  ...              -0.212393              -0.108168
2      2019-05     6169  ...              -0.212393              -0.108168
3      2019-05     4281  ...              -0.212393              -0.108168
4      2019-05     4281  ...              -0.212393              -0.108168
...        ...      ...  ...                    ...                    ...
78324  2020-08    11265  ...              -0.212393              -0.108168
78325  2020-08    15931  ...              -0.212393              -0.108168
78326  2020-08     7202  ...              -0.212393              -0.108168
78327  2020-08     7218  ...              -0.212393              -0.108168
78328  2020-08     7379  ...              -0.212393              -0.108168

[78329 rows x 65 columns]

### Modelo

In [126]:
X = train.drop(["Date","Marca1",	"Marca2",	"Marca3",	"Marca_Inno1",	"Marca_Inno2"], axis=1)
y = train[["Marca1",	"Marca2",	"Marca3",	"Marca_Inno1",	"Marca_Inno2"]]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

#### Knn

In [127]:
from sklearn.neighbors import KNeighborsClassifier
knn1 = KNeighborsClassifier(n_neighbors = 29, weights = 'uniform')
knn1.fit(X_train, y_train)

# Predecimos sobre nuestro set de entrenamieto
y_train_pred = knn1.predict(X_train)

# Predecimos sobre nuestro set de test
y_test_pred = knn1.predict(X_test)

# Comaparamos con las etiquetas reales
print('Accuracy sobre conjunto de Train:', accuracy_score(y_train_pred,y_train))
print('Curva Roc sobre el test set: ', metrics.roc_auc_score(y_test, y_test_pred))

Accuracy sobre conjunto de Train: 0.6917745759620646
Curva Roc sobre el test set:  0.536422277246593

In [128]:
X_tes1 = test.drop(["Date","Marca1",	"Marca2",	"Marca3",	"Marca_Inno1",	"Marca_Inno2"], axis=1)
y_test1 = test[["Marca1",	"Marca2",	"Marca3",	"Marca_Inno1",	"Marca_Inno2"]]

In [129]:
pred = knn1.predict(X_tes1)
pred = pd.DataFrame(pred)
pred

         0    1    2    3    4
0      0.0  0.0  0.0  0.0  0.0
1      0.0  0.0  0.0  0.0  0.0
2      0.0  0.0  1.0  0.0  0.0
3      0.0  0.0  0.0  0.0  0.0
4      0.0  0.0  1.0  0.0  0.0
...    ...  ...  ...  ...  ...
11765  0.0  0.0  1.0  0.0  0.0
11766  0.0  0.0  1.0  0.0  0.0
11767  0.0  0.0  1.0  0.0  0.0
11768  0.0  0.0  1.0  0.0  0.0
11769  0.0  0.0  1.0  0.0  0.0

[11770 rows x 5 columns]

##### GridSearch Knn

In [130]:
%%time

from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

knn1 = KNeighborsClassifier()
knn1.fit(X_train, y_train)

# Define los hyperparámetros

hp_candidates = [{'n_neighbors': np.arange(30, 60, 5),
                  'weights':['uniform','distance']}]

# Se busca mediante GridSearch el mejor hyperparámetro según los ya propuestos
grid = GridSearchCV(estimator=knn1, param_grid=hp_candidates, 
                    scoring="roc_auc", cv=5, verbose=5)

grid.fit(X_train, y_train)

# Se obtiene y se visualizan los mejor hiperparámetros encontrados con GridSearch
print(grid.best_score_)
print(grid.best_estimator_)
print(grid.best_params_)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV] n_neighbors=30, weights=uniform .................................

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.

[CV] ..... n_neighbors=30, weights=uniform, score=0.770, total=   1.6s
[CV] n_neighbors=30, weights=uniform .................................

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    1.6s remaining:    0.0s

[CV] ..... n_neighbors=30, weights=uniform, score=0.772, total=   1.3s
[CV] n_neighbors=30, weights=uniform .................................

[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    3.0s remaining:    0.0s

[CV] ..... n_neighbors=30, weights=uniform, score=0.767, total=   1.4s
[CV] n_neighbors=30, weights=uniform .................................

[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    4.3s remaining:    0.0s

[CV] ..... n_neighbors=30, weights=uniform, score=0.767, total=   1.3s
[CV] n_neighbors=30, weights=uniform .................................

[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    5.6s remaining:    0.0s

[CV] ..... n_neighbors=30, weights=uniform, score=0.772, total=   1.2s
[CV] n_neighbors=30, weights=distance ................................
[CV] .... n_neighbors=30, weights=distance, score=0.924, total=   1.6s
[CV] n_neighbors=30, weights=distance ................................
[CV] .... n_neighbors=30, weights=distance, score=0.927, total=   1.7s
[CV] n_neighbors=30, weights=distance ................................
[CV] .... n_neighbors=30, weights=distance, score=0.922, total=   1.7s
[CV] n_neighbors=30, weights=distance ................................
[CV] .... n_neighbors=30, weights=distance, score=0.922, total=   1.7s
[CV] n_neighbors=30, weights=distance ................................
[CV] .... n_neighbors=30, weights=distance, score=0.923, total=   2.0s
[CV] n_neighbors=35, weights=uniform .................................
[CV] ..... n_neighbors=35, weights=uniform, score=0.753, total=   1.8s
[CV] n_neighbors=35, weights=uniform .................................
[CV] ..... n_neighbors=35, weights=uniform, score=0.754, total=   1.8s
[CV] n_neighbors=35, weights=uniform .................................
[CV] ..... n_neighbors=35, weights=uniform, score=0.751, total=   1.7s
[CV] n_neighbors=35, weights=uniform .................................
[CV] ..... n_neighbors=35, weights=uniform, score=0.749, total=   1.7s
[CV] n_neighbors=35, weights=uniform .................................
[CV] ..... n_neighbors=35, weights=uniform, score=0.753, total=   1.8s
[CV] n_neighbors=35, weights=distance ................................
[CV] .... n_neighbors=35, weights=distance, score=0.926, total=   2.2s
[CV] n_neighbors=35, weights=distance ................................
[CV] .... n_neighbors=35, weights=distance, score=0.929, total=   3.3s
[CV] n_neighbors=35, weights=distance ................................
[CV] .... n_neighbors=35, weights=distance, score=0.927, total=   2.0s
[CV] n_neighbors=35, weights=distance ................................
[CV] .... n_neighbors=35, weights=distance, score=0.928, total=   1.4s
[CV] n_neighbors=35, weights=distance ................................
[CV] .... n_neighbors=35, weights=distance, score=0.926, total=   1.8s
[CV] n_neighbors=40, weights=uniform .................................
[CV] ..... n_neighbors=40, weights=uniform, score=0.734, total=   1.4s
[CV] n_neighbors=40, weights=uniform .................................
[CV] ..... n_neighbors=40, weights=uniform, score=0.736, total=   1.4s
[CV] n_neighbors=40, weights=uniform .................................
[CV] ..... n_neighbors=40, weights=uniform, score=0.734, total=   1.5s
[CV] n_neighbors=40, weights=uniform .................................
[CV] ..... n_neighbors=40, weights=uniform, score=0.731, total=   1.4s
[CV] n_neighbors=40, weights=uniform .................................
[CV] ..... n_neighbors=40, weights=uniform, score=0.737, total=   1.4s
[CV] n_neighbors=40, weights=distance ................................
[CV] .... n_neighbors=40, weights=distance, score=0.926, total=   1.4s
[CV] n_neighbors=40, weights=distance ................................
[CV] .... n_neighbors=40, weights=distance, score=0.931, total=   1.3s
[CV] n_neighbors=40, weights=distance ................................
[CV] .... n_neighbors=40, weights=distance, score=0.931, total=   1.4s
[CV] n_neighbors=40, weights=distance ................................
[CV] .... n_neighbors=40, weights=distance, score=0.930, total=   1.3s
[CV] n_neighbors=40, weights=distance ................................
[CV] .... n_neighbors=40, weights=distance, score=0.930, total=   1.4s
[CV] n_neighbors=45, weights=uniform .................................
[CV] ..... n_neighbors=45, weights=uniform, score=0.720, total=   1.3s
[CV] n_neighbors=45, weights=uniform .................................
[CV] ..... n_neighbors=45, weights=uniform, score=0.722, total=   1.4s
[CV] n_neighbors=45, weights=uniform .................................
[CV] ..... n_neighbors=45, weights=uniform, score=0.720, total=   1.3s
[CV] n_neighbors=45, weights=uniform .................................
[CV] ..... n_neighbors=45, weights=uniform, score=0.716, total=   1.3s
[CV] n_neighbors=45, weights=uniform .................................
[CV] ..... n_neighbors=45, weights=uniform, score=0.722, total=   1.4s
[CV] n_neighbors=45, weights=distance ................................
[CV] .... n_neighbors=45, weights=distance, score=0.929, total=   1.3s
[CV] n_neighbors=45, weights=distance ................................
[CV] .... n_neighbors=45, weights=distance, score=0.935, total=   1.3s
[CV] n_neighbors=45, weights=distance ................................
[CV] .... n_neighbors=45, weights=distance, score=0.933, total=   1.3s
[CV] n_neighbors=45, weights=distance ................................
[CV] .... n_neighbors=45, weights=distance, score=0.933, total=   1.2s
[CV] n_neighbors=45, weights=distance ................................
[CV] .... n_neighbors=45, weights=distance, score=0.931, total=   1.3s
[CV] n_neighbors=50, weights=uniform .................................
[CV] ..... n_neighbors=50, weights=uniform, score=0.707, total=   1.3s
[CV] n_neighbors=50, weights=uniform .................................
[CV] ..... n_neighbors=50, weights=uniform, score=0.708, total=   1.3s
[CV] n_neighbors=50, weights=uniform .................................
[CV] ..... n_neighbors=50, weights=uniform, score=0.708, total=   1.3s
[CV] n_neighbors=50, weights=uniform .................................
[CV] ..... n_neighbors=50, weights=uniform, score=0.704, total=   1.3s
[CV] n_neighbors=50, weights=uniform .................................
[CV] ..... n_neighbors=50, weights=uniform, score=0.710, total=   1.3s
[CV] n_neighbors=50, weights=distance ................................
[CV] .... n_neighbors=50, weights=distance, score=0.931, total=   1.3s
[CV] n_neighbors=50, weights=distance ................................
[CV] .... n_neighbors=50, weights=distance, score=0.936, total=   1.3s
[CV] n_neighbors=50, weights=distance ................................
[CV] .... n_neighbors=50, weights=distance, score=0.937, total=   1.3s
[CV] n_neighbors=50, weights=distance ................................
[CV] .... n_neighbors=50, weights=distance, score=0.934, total=   1.3s
[CV] n_neighbors=50, weights=distance ................................
[CV] .... n_neighbors=50, weights=distance, score=0.934, total=   1.3s
[CV] n_neighbors=55, weights=uniform .................................
[CV] ..... n_neighbors=55, weights=uniform, score=0.696, total=   1.3s
[CV] n_neighbors=55, weights=uniform .................................
[CV] ..... n_neighbors=55, weights=uniform, score=0.698, total=   1.3s
[CV] n_neighbors=55, weights=uniform .................................
[CV] ..... n_neighbors=55, weights=uniform, score=0.698, total=   1.3s
[CV] n_neighbors=55, weights=uniform .................................
[CV] ..... n_neighbors=55, weights=uniform, score=0.692, total=   1.3s
[CV] n_neighbors=55, weights=uniform .................................
[CV] ..... n_neighbors=55, weights=uniform, score=0.700, total=   1.3s
[CV] n_neighbors=55, weights=distance ................................
[CV] .... n_neighbors=55, weights=distance, score=0.934, total=   1.3s
[CV] n_neighbors=55, weights=distance ................................
[CV] .... n_neighbors=55, weights=distance, score=0.938, total=   1.3s
[CV] n_neighbors=55, weights=distance ................................
[CV] .... n_neighbors=55, weights=distance, score=0.938, total=   1.3s
[CV] n_neighbors=55, weights=distance ................................
[CV] .... n_neighbors=55, weights=distance, score=0.936, total=   1.3s
[CV] n_neighbors=55, weights=distance ................................
[CV] .... n_neighbors=55, weights=distance, score=0.936, total=   1.3s

[Parallel(n_jobs=1)]: Done  60 out of  60 | elapsed:  1.5min finished

0.9362708093965217
KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=55, p=2,
                     weights='distance')
{'n_neighbors': 55, 'weights': 'distance'}
CPU times: user 1min 28s, sys: 338 ms, total: 1min 29s
Wall time: 1min 30s

In [132]:
knn1 = KNeighborsClassifier(n_neighbors = 55, weights = 'distance')
knn1.fit(X_train, y_train)

# Predecimos sobre nuestro set de entrenamieto
y_train_pred = knn1.predict(X_train)

# Predecimos sobre nuestro set de test
y_test_pred = knn1.predict(X_test)

# Comaparamos con las etiquetas reales
print('Accuracy sobre conjunto de Train:', accuracy_score(y_train_pred,y_train))
print('Curva Roc sobre el test set: ', metrics.roc_auc_score(y_test, y_test_pred))

Accuracy sobre conjunto de Train: 1.0
Curva Roc sobre el test set:  0.7258228700438482

In [135]:
X_tes1 = test.drop(["Date","Marca1",	"Marca2",	"Marca3",	"Marca_Inno1",	"Marca_Inno2"], axis=1)
y_test1 = test[["Marca1",	"Marca2",	"Marca3",	"Marca_Inno1",	"Marca_Inno2"]]

pred1 = knn1.predict(X_tes1)
pred1 = pd.DataFrame(pred)
pred1

         0    1    2    3    4
0      0.0  0.0  0.0  0.0  0.0
1      0.0  0.0  0.0  0.0  0.0
2      0.0  0.0  1.0  0.0  0.0
3      0.0  0.0  0.0  0.0  0.0
4      0.0  0.0  1.0  0.0  0.0
...    ...  ...  ...  ...  ...
11765  0.0  0.0  1.0  0.0  0.0
11766  0.0  0.0  1.0  0.0  0.0
11767  0.0  0.0  1.0  0.0  0.0
11768  0.0  0.0  1.0  0.0  0.0
11769  0.0  0.0  1.0  0.0  0.0

[11770 rows x 5 columns]

In [140]:
testeo_kn = X_tes2.merge(pred2, how = 'left',left_index = True, right_index = True)
testeo_kn = testeo_kn.rename(columns={0:"Marca1", 1:"Marca2", 2:"Marca3", 3:"Marca_Inno1", 4:"Marca_Inno2"})
testeo_kn

       Cliente  Marca2_x  CapacidadEnvase2  ...  Marca3  Marca_Inno1  Marca_Inno2
0        18792  0.580011         -0.045690  ...     0.0          0.0          0.0
1        19319  0.580011         -0.045690  ...     0.0          0.0          0.0
2        14998  0.017220         -0.642172  ...     1.0          0.0          0.0
3        19187 -0.076578         -0.642172  ...     0.0          0.0          0.0
4        14663  0.580011         -0.045690  ...     1.0          0.0          0.0
...        ...       ...               ...  ...     ...          ...          ...
11765    11124 -0.076578         -0.642172  ...     1.0          0.0          0.0
11766    11066 -0.076578         -0.642172  ...     1.0          0.0          0.0
11767    11085 -0.076578         -0.642172  ...     1.0          0.0          0.0
11768     1605  0.580011         -0.045690  ...     1.0          0.0          0.0
11769    10993  0.017220         -0.642172  ...     1.0          0.0          0.0

[11770 rows x 64 columns]

In [159]:
testeo_kn = testeo_kn[["Cliente","Marca1",	"Marca2",	"Marca3",	"Marca_Inno1",	"Marca_Inno2"]]
testeo_kn

      Cliente  Marca1  Marca2  Marca3  Marca_Inno1  Marca_Inno2
9820        1     0.0     0.0     0.0          0.0          0.0
9818        1     0.0     0.0     0.0          0.0          0.0
9823        2     0.0     0.0     0.0          0.0          0.0
9825        3     0.0     0.0     0.0          0.0          0.0
9828        3     0.0     0.0     0.0          0.0          0.0
...       ...     ...     ...     ...          ...          ...
39      20434     0.0     0.0     0.0          1.0          0.0
29      20456     0.0     0.0     0.0          1.0          0.0
65      20456     0.0     0.0     0.0          0.0          1.0
5165    20580     0.0     0.0     0.0          1.0          0.0
3104    20580     0.0     0.0     0.0          1.0          0.0

[11770 rows x 6 columns]

In [198]:
testeo_2 = testeo.drop(["Marca1",	"Marca2",	"Marca3",	"Marca_Inno1",	"Marca_Inno2"], axis=1)
testeo_2

      Cliente
0          10
1          12
2          14
3          15
4          18
...       ...
9297    20186
9298    20261
9299    20309
9300    20360
9301    20569

[9302 rows x 1 columns]

In [199]:
testeo_3 = pd.merge(testeo_2, testeo_kn,  how='inner', on=['Cliente'])
testeo_3

      Cliente  Marca1  Marca2  Marca3  Marca_Inno1  Marca_Inno2
0          14     0.0     0.0     0.0          0.0          0.0
1          15     0.0     0.0     1.0          0.0          0.0
2          35     0.0     0.0     1.0          0.0          0.0
3          40     0.0     0.0     1.0          0.0          0.0
4         150     0.0     0.0     1.0          0.0          0.0
...       ...     ...     ...     ...          ...          ...
9619    20261     0.0     0.0     0.0          0.0          1.0
9620    20309     0.0     0.0     0.0          1.0          0.0
9621    20309     0.0     0.0     0.0          0.0          1.0
9622    20360     0.0     0.0     0.0          0.0          1.0
9623    20360     0.0     0.0     0.0          1.0          0.0

[9624 rows x 6 columns]

In [200]:
testeo_3 = testeo_3.drop(["Cliente"], axis=1)
testeo_3

      Marca1  Marca2  Marca3  Marca_Inno1  Marca_Inno2
0        0.0     0.0     0.0          0.0          0.0
1        0.0     0.0     1.0          0.0          0.0
2        0.0     0.0     1.0          0.0          0.0
3        0.0     0.0     1.0          0.0          0.0
4        0.0     0.0     1.0          0.0          0.0
...      ...     ...     ...          ...          ...
9619     0.0     0.0     0.0          0.0          1.0
9620     0.0     0.0     0.0          1.0          0.0
9621     0.0     0.0     0.0          0.0          1.0
9622     0.0     0.0     0.0          0.0          1.0
9623     0.0     0.0     0.0          1.0          0.0

[9624 rows x 5 columns]

In [201]:
testeo_2 = testeo_2.merge(testeo_3, left_index=True, right_index=True)
testeo_2

      Cliente  Marca1  Marca2  Marca3  Marca_Inno1  Marca_Inno2
0          10     0.0     0.0     0.0          0.0          0.0
1          12     0.0     0.0     1.0          0.0          0.0
2          14     0.0     0.0     1.0          0.0          0.0
3          15     0.0     0.0     1.0          0.0          0.0
4          18     0.0     0.0     1.0          0.0          0.0
...       ...     ...     ...     ...          ...          ...
9297    20186     0.0     0.0     1.0          0.0          0.0
9298    20261     0.0     0.0     1.0          0.0          0.0
9299    20309     0.0     0.0     1.0          0.0          0.0
9300    20360     0.0     0.0     1.0          0.0          0.0
9301    20569     0.0     0.0     1.0          0.0          0.0

[9302 rows x 6 columns]

In [202]:
testeo_2.to_csv("testinkn2.csv", sep=',', index=False)

#### Random Forest

In [161]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(max_depth=18, n_estimators=28)
clf.fit(X_train,y_train)

# Predecimos sobre nuestro set de entrenamieto
y_train_pred = clf.predict(X_train)

# Predecimos sobre nuestro set de test
y_test_pred = clf.predict(X_test)

# Comaparamos con las etiquetas reales
print('Accuracy sobre conjunto de Train:', accuracy_score(y_train_pred,y_train))
print('Curva Roc sobre el test set: ', metrics.roc_auc_score(y_test, y_test_pred))

Accuracy sobre conjunto de Train: 1.0
Curva Roc sobre el test set:  1.0

In [162]:
X_tes2 = test.drop(["Date","Marca1",	"Marca2",	"Marca3",	"Marca_Inno1",	"Marca_Inno2"], axis=1)
y_test2 = test[["Marca1",	"Marca2",	"Marca3",	"Marca_Inno1",	"Marca_Inno2"]]

pred2 = clf.predict(X_tes1)
pred2 = pd.DataFrame(pred)
pred2

         0    1    2    3    4
0      0.0  0.0  0.0  0.0  0.0
1      0.0  0.0  0.0  0.0  0.0
2      0.0  0.0  1.0  0.0  0.0
3      0.0  0.0  0.0  0.0  0.0
4      0.0  0.0  1.0  0.0  0.0
...    ...  ...  ...  ...  ...
11765  0.0  0.0  1.0  0.0  0.0
11766  0.0  0.0  1.0  0.0  0.0
11767  0.0  0.0  1.0  0.0  0.0
11768  0.0  0.0  1.0  0.0  0.0
11769  0.0  0.0  1.0  0.0  0.0

[11770 rows x 5 columns]

In [163]:
X_test_rnf = testeo_1.drop(["Date","Marca1",	"Marca2",	"Marca3",	"Marca_Inno1",	"Marca_Inno2"], axis=1)
y_test_rnf = testeo_1[["Marca1",	"Marca2",	"Marca3",	"Marca_Inno1",	"Marca_Inno2"]]

pred_rnf = clf.predict(X_test_rnf)
pred_rnf = pd.DataFrame(pred_rnf)
pred_rnf

        0    1    2    3    4
0     0.0  0.0  1.0  0.0  0.0
1     0.0  0.0  1.0  0.0  0.0
2     0.0  0.0  1.0  0.0  0.0
3     0.0  0.0  1.0  0.0  0.0
4     0.0  0.0  1.0  0.0  0.0
...   ...  ...  ...  ...  ...
9297  0.0  0.0  1.0  0.0  0.0
9298  0.0  0.0  1.0  0.0  0.0
9299  0.0  0.0  1.0  0.0  0.0
9300  0.0  0.0  1.0  0.0  0.0
9301  0.0  0.0  1.0  0.0  0.0

[9302 rows x 5 columns]

#### XGBoost

In [164]:
from xgboost import XGBClassifier
from sklearn.multioutput import MultiOutputClassifier 
xgs = MultiOutputClassifier(XGBClassifier(max_depth=18, n_estimators=20))
xgs.fit(X_train,y_train)

# Predecimos sobre nuestro set de entrenamieto
y_train_pred = xgs.predict(X_train)

# Predecimos sobre nuestro set de test
y_test_pred = xgs.predict(X_test)

# Comaparamos con las etiquetas reales
print('Accuracy sobre el test set: ',metrics.accuracy_score(y_test, y_test_pred))
print('Curva Roc sobre el test set: ', metrics.roc_auc_score(y_test, y_test_pred))

Accuracy sobre el test set:  1.0
Curva Roc sobre el test set:  1.0

In [165]:
X_tes3 = test.drop(["Date","Marca1",	"Marca2",	"Marca3",	"Marca_Inno1",	"Marca_Inno2"], axis=1)
y_test3 = test[["Marca1",	"Marca2",	"Marca3",	"Marca_Inno1",	"Marca_Inno2"]]

pred3 = xgs.predict(X_tes3)
pred3 = pd.DataFrame(pred)
pred3

         0    1    2    3    4
0      0.0  0.0  0.0  0.0  0.0
1      0.0  0.0  0.0  0.0  0.0
2      0.0  0.0  1.0  0.0  0.0
3      0.0  0.0  0.0  0.0  0.0
4      0.0  0.0  1.0  0.0  0.0
...    ...  ...  ...  ...  ...
11765  0.0  0.0  1.0  0.0  0.0
11766  0.0  0.0  1.0  0.0  0.0
11767  0.0  0.0  1.0  0.0  0.0
11768  0.0  0.0  1.0  0.0  0.0
11769  0.0  0.0  1.0  0.0  0.0

[11770 rows x 5 columns]

In [185]:
testeo_2 = testeo.drop(["Marca1",	"Marca2",	"Marca3",	"Marca_Inno1",	"Marca_Inno2"], axis=1)
testeo_2

      Cliente
0          10
1          12
2          14
3          15
4          18
...       ...
9297    20186
9298    20261
9299    20309
9300    20360
9301    20569

[9302 rows x 1 columns]

In [186]:
testeo_2 = testeo_2.merge(pred3, left_index=True, right_index=True)
testeo_2 = testeo_2.rename(columns={0:"Marca1", 1:"Marca2", 2:"Marca3", 3:"Marca_Inno1", 4:"Marca_Inno2"})
testeo_2

      Cliente  Marca1  Marca2  Marca3  Marca_Inno1  Marca_Inno2
0          10     0.0     0.0     0.0          0.0          0.0
1          12     0.0     0.0     0.0          0.0          0.0
2          14     0.0     0.0     1.0          0.0          0.0
3          15     0.0     0.0     0.0          0.0          0.0
4          18     0.0     0.0     1.0          0.0          0.0
...       ...     ...     ...     ...          ...          ...
9297    20186     0.0     0.0     1.0          0.0          0.0
9298    20261     0.0     0.0     1.0          0.0          0.0
9299    20309     0.0     0.0     1.0          0.0          0.0
9300    20360     0.0     0.0     1.0          0.0          0.0
9301    20569     0.0     0.0     1.0          0.0          0.0

[9302 rows x 6 columns]

In [188]:
testeo_2.to_csv("testinxgs2.csv", sep=',', index=False)

In [166]:
testeo_1

         Date  Cliente  ...  Categoria_Categoria_5  Categoria_Categoria_6
0     2020-10     4045  ...          -1.644282e-17          -9.463493e-18
1     2020-10     1972  ...          -1.644282e-17          -9.463493e-18
2     2020-10      526  ...          -1.644282e-17          -9.463493e-18
3     2020-10     2228  ...          -1.644282e-17          -9.463493e-18
4     2020-10     4385  ...          -1.644282e-17          -9.463493e-18
...       ...      ...  ...                    ...                    ...
9297  2020-10     7426  ...          -1.644282e-17          -9.463493e-18
9298  2020-10     7425  ...          -1.644282e-17          -9.463493e-18
9299  2020-10     7424  ...          -1.644282e-17          -9.463493e-18
9300  2020-10     7432  ...          -1.644282e-17          -9.463493e-18
9301  2020-10        1  ...          -1.644282e-17          -9.463493e-18

[9302 rows x 65 columns]

In [167]:
X_test_xgb = testeo_1.drop(["Date","Marca1",	"Marca2",	"Marca3",	"Marca_Inno1",	"Marca_Inno2"], axis=1)
y_test_xgb = testeo_1[["Marca1",	"Marca2",	"Marca3",	"Marca_Inno1",	"Marca_Inno2"]]

pred_xgb = xgs.predict(X_test_xgb)
pred_xgb = pd.DataFrame(pred_xgb)
pred_xgb

        0    1    2    3    4
0     0.0  0.0  0.0  0.0  0.0
1     0.0  0.0  0.0  0.0  0.0
2     0.0  0.0  0.0  0.0  0.0
3     0.0  0.0  0.0  0.0  0.0
4     0.0  0.0  0.0  0.0  0.0
...   ...  ...  ...  ...  ...
9297  0.0  0.0  0.0  0.0  0.0
9298  0.0  0.0  0.0  0.0  0.0
9299  0.0  0.0  0.0  0.0  0.0
9300  0.0  0.0  0.0  0.0  0.0
9301  0.0  0.0  0.0  0.0  0.0

[9302 rows x 5 columns]

In [174]:
testeo_xgb = X_testeoxgb.merge(y_pred_xgb, how = 'left',left_index = True, right_index = True)
testeo_xgb = testeo_xgb.rename(columns={0:"Marca1", 1:"Marca2", 2:"Marca3", 3:"Marca_Inno1", 4:"Marca_Inno2"})
testeo_xgb

      Cliente      Marca2_x  CapacidadEnvase2  ...  Marca3  Marca_Inno1  Marca_Inno2
0        9510  6.435175e-17      3.154498e-17  ...     0.0          0.0          0.0
1        9512  6.435175e-17      3.154498e-17  ...     0.0          0.0          0.0
2        9444  6.435175e-17      3.154498e-17  ...     0.0          0.0          0.0
3        9513  6.435175e-17      3.154498e-17  ...     0.0          0.0          0.0
4        9514  6.435175e-17      3.154498e-17  ...     0.0          0.0          0.0
...       ...           ...               ...  ...     ...          ...          ...
9297    15756  6.435175e-17      3.154498e-17  ...     0.0          0.0          0.0
9298    15760  6.435175e-17      3.154498e-17  ...     0.0          0.0          0.0
9299    15764  6.435175e-17      3.154498e-17  ...     0.0          0.0          0.0
9300    15950  6.435175e-17      3.154498e-17  ...     0.0          0.0          0.0
9301    20569  6.435175e-17      3.154498e-17  ...     0.0          0.0          0.0

[9302 rows x 64 columns]

In [176]:
testeo_xgb = testeo_xgb[["Cliente","Marca1",	"Marca2",	"Marca3",	"Marca_Inno1",	"Marca_Inno2"]]

In [177]:
testeo_xgb.to_csv("testinxgs.csv", sep=',', index=False)